// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: continuoustracking/v1/frame.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FrameReady is published to Redis Streams by the rtsp-ingress Go service
// when a new frame is available for processing. The tracking-orchestrator
// consumes this from the frame-pipeline stream.
type FrameReady struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Which camera stream this frame belongs to.
	CameraId string `protobuf:"bytes,1,opt,name=camera_id,json=cameraId,proto3" json:"camera_id,omitempty"`
	// MinIO key where the frame JPEG/PNG is stored.
	MinioKey string `protobuf:"bytes,2,opt,name=minio_key,json=minioKey,proto3" json:"minio_key,omitempty"`
	// Frame index (monotonically increasing per camera).
	FrameIndex int64 `protobuf:"varint,3,opt,name=frame_index,json=frameIndex,proto3" json:"frame_index,omitempty"`
	// Capture timestamp from RTSP source (nanoseconds since Unix epoch).
	CaptureTimeUnixNs uint64 `protobuf:"fixed64,4,opt,name=capture_time_unix_ns,json=captureTimeUnixNs,proto3" json:"capture_time_unix_ns,omitempty"`
	// Wall-clock time when ingress received the frame (nanoseconds).
	ReceivedTimeUnixNs uint64 `protobuf:"fixed64,5,opt,name=received_time_unix_ns,json=receivedTimeUnixNs,proto3" json:"received_time_unix_ns,omitempty"`
	// Frame dimensions.
	Width  int32 `protobuf:"varint,6,opt,name=width,proto3" json:"width,omitempty"`
	Height int32 `protobuf:"varint,7,opt,name=height,proto3" json:"height,omitempty"`
	// Frame rate at which this frame was extracted (0 = all frames).
	SampleFps     float32 `protobuf:"fixed32,8,opt,name=sample_fps,json=sampleFps,proto3" json:"sample_fps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrameReady) Reset() {
	*x = FrameReady{}
	mi := &file_continuoustracking_v1_frame_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrameReady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameReady) ProtoMessage() {}

func (x *FrameReady) ProtoReflect() protoreflect.Message {
	mi := &file_continuoustracking_v1_frame_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameReady.ProtoReflect.Descriptor instead.
func (*FrameReady) Descriptor() ([]byte, []int) {
	return file_continuoustracking_v1_frame_proto_rawDescGZIP(), []int{0}
}

func (x *FrameReady) GetCameraId() string {
	if x != nil {
		return x.CameraId
	}
	return ""
}

func (x *FrameReady) GetMinioKey() string {
	if x != nil {
		return x.MinioKey
	}
	return ""
}

func (x *FrameReady) GetFrameIndex() int64 {
	if x != nil {
		return x.FrameIndex
	}
	return 0
}

func (x *FrameReady) GetCaptureTimeUnixNs() uint64 {
	if x != nil {
		return x.CaptureTimeUnixNs
	}
	return 0
}

func (x *FrameReady) GetReceivedTimeUnixNs() uint64 {
	if x != nil {
		return x.ReceivedTimeUnixNs
	}
	return 0
}

func (x *FrameReady) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *FrameReady) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *FrameReady) GetSampleFps() float32 {
	if x != nil {
		return x.SampleFps
	}
	return 0
}

// FrameResponse is published back to Redis Streams by the
// tracking-orchestrator after processing. The rtsp-ingress may use this
// for acknowledgment and metrics.
type FrameResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Correlates to the FrameReady frame_index + camera_id.
	CameraId   string `protobuf:"bytes,1,opt,name=camera_id,json=cameraId,proto3" json:"camera_id,omitempty"`
	FrameIndex int64  `protobuf:"varint,2,opt,name=frame_index,json=frameIndex,proto3" json:"frame_index,omitempty"`
	// Whether processing succeeded.
	Success bool `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	// If not success, a brief error code.
	ErrorCode string `protobuf:"bytes,4,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	// Processing latency in microseconds.
	ProcessingLatencyUs int64 `protobuf:"varint,5,opt,name=processing_latency_us,json=processingLatencyUs,proto3" json:"processing_latency_us,omitempty"`
	// Number of detections produced.
	DetectionCount int32 `protobuf:"varint,6,opt,name=detection_count,json=detectionCount,proto3" json:"detection_count,omitempty"`
	// Wall-clock time when processing completed.
	CompletedTimeUnixNs uint64 `protobuf:"fixed64,7,opt,name=completed_time_unix_ns,json=completedTimeUnixNs,proto3" json:"completed_time_unix_ns,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *FrameResponse) Reset() {
	*x = FrameResponse{}
	mi := &file_continuoustracking_v1_frame_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameResponse) ProtoMessage() {}

func (x *FrameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_continuoustracking_v1_frame_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameResponse.ProtoReflect.Descriptor instead.
func (*FrameResponse) Descriptor() ([]byte, []int) {
	return file_continuoustracking_v1_frame_proto_rawDescGZIP(), []int{1}
}

func (x *FrameResponse) GetCameraId() string {
	if x != nil {
		return x.CameraId
	}
	return ""
}

func (x *FrameResponse) GetFrameIndex() int64 {
	if x != nil {
		return x.FrameIndex
	}
	return 0
}

func (x *FrameResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FrameResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *FrameResponse) GetProcessingLatencyUs() int64 {
	if x != nil {
		return x.ProcessingLatencyUs
	}
	return 0
}

func (x *FrameResponse) GetDetectionCount() int32 {
	if x != nil {
		return x.DetectionCount
	}
	return 0
}

func (x *FrameResponse) GetCompletedTimeUnixNs() uint64 {
	if x != nil {
		return x.CompletedTimeUnixNs
	}
	return 0
}

var File_continuoustracking_v1_frame_proto protoreflect.FileDescriptor

const file_continuoustracking_v1_frame_proto_rawDesc = "" +
	"\n" +
	"!continuoustracking/v1/frame.proto\x12\x15continuoustracking.v1\"\x98\x02\n" +
	"\n" +
	"FrameReady\x12\x1b\n" +
	"\tcamera_id\x18\x01 \x01(\tR\bcameraId\x12\x1b\n" +
	"\tminio_key\x18\x02 \x01(\tR\bminioKey\x12\x1f\n" +
	"\vframe_index\x18\x03 \x01(\x03R\n" +
	"frameIndex\x12/\n" +
	"\x14capture_time_unix_ns\x18\x04 \x01(\x06R\x11captureTimeUnixNs\x121\n" +
	"\x15received_time_unix_ns\x18\x05 \x01(\x06R\x12receivedTimeUnixNs\x12\x14\n" +
	"\x05width\x18\x06 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\a \x01(\x05R\x06height\x12\x1d\n" +
	"\n" +
	"sample_fps\x18\b \x01(\x02R\tsampleFps\"\x98\x02\n" +
	"\rFrameResponse\x12\x1b\n" +
	"\tcamera_id\x18\x01 \x01(\tR\bcameraId\x12\x1f\n" +
	"\vframe_index\x18\x02 \x01(\x03R\n" +
	"frameIndex\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"error_code\x18\x04 \x01(\tR\terrorCode\x122\n" +
	"\x15processing_latency_us\x18\x05 \x01(\x03R\x13processingLatencyUs\x12'\n" +
	"\x0fdetection_count\x18\x06 \x01(\x05R\x0edetectionCount\x123\n" +
	"\x16completed_time_unix_ns\x18\a \x01(\x06R\x13completedTimeUnixNsBDZBgithub.com/khoofia/continuous-tracking/proto/continuoustracking/v1b\x06proto3"

var (
	file_continuoustracking_v1_frame_proto_rawDescOnce sync.Once
	file_continuoustracking_v1_frame_proto_rawDescData []byte
)

func file_continuoustracking_v1_frame_proto_rawDescGZIP() []byte {
	file_continuoustracking_v1_frame_proto_rawDescOnce.Do(func() {
		file_continuoustracking_v1_frame_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_continuoustracking_v1_frame_proto_rawDesc), len(file_continuoustracking_v1_frame_proto_rawDesc)))
	})
	return file_continuoustracking_v1_frame_proto_rawDescData
}

var file_continuoustracking_v1_frame_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_continuoustracking_v1_frame_proto_goTypes = []any{
	(*FrameReady)(nil),    // 0: continuoustracking.v1.FrameReady
	(*FrameResponse)(nil), // 1: continuoustracking.v1.FrameResponse
}
var file_continuoustracking_v1_frame_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_continuoustracking_v1_frame_proto_init() }
func file_continuoustracking_v1_frame_proto_init() {
	if File_continuoustracking_v1_frame_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_continuoustracking_v1_frame_proto_rawDesc), len(file_continuoustracking_v1_frame_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_continuoustracking_v1_frame_proto_goTypes,
		DependencyIndexes: file_continuoustracking_v1_frame_proto_depIdxs,
		MessageInfos:      file_continuoustracking_v1_frame_proto_msgTypes,
	}.Build()
	File_continuoustracking_v1_frame_proto = out.File
	file_continuoustracking_v1_frame_proto_goTypes = nil
	file_continuoustracking_v1_frame_proto_depIdxs = nil
}
