// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: continuoustracking/v1/scene.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TagReason int32

const (
	TagReason_TAG_REASON_UNSPECIFIED      TagReason = 0
	TagReason_TAG_REASON_PERIODIC         TagReason = 1
	TagReason_TAG_REASON_IDENTITY_CHANGED TagReason = 2
	TagReason_TAG_REASON_HAZARD           TagReason = 3
	TagReason_TAG_REASON_DWELL_START      TagReason = 4
	TagReason_TAG_REASON_FALL             TagReason = 5
	TagReason_TAG_REASON_DEMENTIA_SIGNAL  TagReason = 6
)

// Enum value maps for TagReason.
var (
	TagReason_name = map[int32]string{
		0: "TAG_REASON_UNSPECIFIED",
		1: "TAG_REASON_PERIODIC",
		2: "TAG_REASON_IDENTITY_CHANGED",
		3: "TAG_REASON_HAZARD",
		4: "TAG_REASON_DWELL_START",
		5: "TAG_REASON_FALL",
		6: "TAG_REASON_DEMENTIA_SIGNAL",
	}
	TagReason_value = map[string]int32{
		"TAG_REASON_UNSPECIFIED":      0,
		"TAG_REASON_PERIODIC":         1,
		"TAG_REASON_IDENTITY_CHANGED": 2,
		"TAG_REASON_HAZARD":           3,
		"TAG_REASON_DWELL_START":      4,
		"TAG_REASON_FALL":             5,
		"TAG_REASON_DEMENTIA_SIGNAL":  6,
	}
)

func (x TagReason) Enum() *TagReason {
	p := new(TagReason)
	*p = x
	return p
}

func (x TagReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TagReason) Descriptor() protoreflect.EnumDescriptor {
	return file_continuoustracking_v1_scene_proto_enumTypes[0].Descriptor()
}

func (TagReason) Type() protoreflect.EnumType {
	return &file_continuoustracking_v1_scene_proto_enumTypes[0]
}

func (x TagReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TagReason.Descriptor instead.
func (TagReason) EnumDescriptor() ([]byte, []int) {
	return file_continuoustracking_v1_scene_proto_rawDescGZIP(), []int{0}
}

// SceneSample is published to the scene.samples Redis Stream by the
// orchestrator's KeyframeSampler. The scene worker (currently in
// Cognitive Companion as CTSSceneWorker) fetches the JPEG from MinIO and
// runs scene analysis on tagged frames.
type SceneSample struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique keyframe ID (ULID or UUID).
	KeyframeId string `protobuf:"bytes,1,opt,name=keyframe_id,json=keyframeId,proto3" json:"keyframe_id,omitempty"`
	// Originating tracklet and global track. Both required.
	TrackletId    string `protobuf:"bytes,2,opt,name=tracklet_id,json=trackletId,proto3" json:"tracklet_id,omitempty"`
	GlobalTrackId string `protobuf:"bytes,3,opt,name=global_track_id,json=globalTrackId,proto3" json:"global_track_id,omitempty"`
	// Originating camera.
	CameraId string `protobuf:"bytes,4,opt,name=camera_id,json=cameraId,proto3" json:"camera_id,omitempty"`
	// MinIO object key for the JPEG.
	MinioKey string `protobuf:"bytes,5,opt,name=minio_key,json=minioKey,proto3" json:"minio_key,omitempty"`
	// Capture wall clock in unix nanoseconds.
	CapturedAtUnixNs uint64 `protobuf:"fixed64,6,opt,name=captured_at_unix_ns,json=capturedAtUnixNs,proto3" json:"captured_at_unix_ns,omitempty"`
	// Why this frame was sampled.
	TagReason TagReason `protobuf:"varint,7,opt,name=tag_reason,json=tagReason,proto3,enum=continuoustracking.v1.TagReason" json:"tag_reason,omitempty"`
	// Annotations envelope (bbox, person_id, posture, activity, confidence)
	// serialised as JSON for forward-compat with future detector schemas.
	AnnotationsJson string `protobuf:"bytes,8,opt,name=annotations_json,json=annotationsJson,proto3" json:"annotations_json,omitempty"`
	// Retention deadline in unix nanoseconds.
	ExpiresAtUnixNs uint64 `protobuf:"fixed64,9,opt,name=expires_at_unix_ns,json=expiresAtUnixNs,proto3" json:"expires_at_unix_ns,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SceneSample) Reset() {
	*x = SceneSample{}
	mi := &file_continuoustracking_v1_scene_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SceneSample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SceneSample) ProtoMessage() {}

func (x *SceneSample) ProtoReflect() protoreflect.Message {
	mi := &file_continuoustracking_v1_scene_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SceneSample.ProtoReflect.Descriptor instead.
func (*SceneSample) Descriptor() ([]byte, []int) {
	return file_continuoustracking_v1_scene_proto_rawDescGZIP(), []int{0}
}

func (x *SceneSample) GetKeyframeId() string {
	if x != nil {
		return x.KeyframeId
	}
	return ""
}

func (x *SceneSample) GetTrackletId() string {
	if x != nil {
		return x.TrackletId
	}
	return ""
}

func (x *SceneSample) GetGlobalTrackId() string {
	if x != nil {
		return x.GlobalTrackId
	}
	return ""
}

func (x *SceneSample) GetCameraId() string {
	if x != nil {
		return x.CameraId
	}
	return ""
}

func (x *SceneSample) GetMinioKey() string {
	if x != nil {
		return x.MinioKey
	}
	return ""
}

func (x *SceneSample) GetCapturedAtUnixNs() uint64 {
	if x != nil {
		return x.CapturedAtUnixNs
	}
	return 0
}

func (x *SceneSample) GetTagReason() TagReason {
	if x != nil {
		return x.TagReason
	}
	return TagReason_TAG_REASON_UNSPECIFIED
}

func (x *SceneSample) GetAnnotationsJson() string {
	if x != nil {
		return x.AnnotationsJson
	}
	return ""
}

func (x *SceneSample) GetExpiresAtUnixNs() uint64 {
	if x != nil {
		return x.ExpiresAtUnixNs
	}
	return 0
}

var File_continuoustracking_v1_scene_proto protoreflect.FileDescriptor

const file_continuoustracking_v1_scene_proto_rawDesc = "" +
	"\n" +
	"!continuoustracking/v1/scene.proto\x12\x15continuoustracking.v1\"\xf9\x02\n" +
	"\vSceneSample\x12\x1f\n" +
	"\vkeyframe_id\x18\x01 \x01(\tR\n" +
	"keyframeId\x12\x1f\n" +
	"\vtracklet_id\x18\x02 \x01(\tR\n" +
	"trackletId\x12&\n" +
	"\x0fglobal_track_id\x18\x03 \x01(\tR\rglobalTrackId\x12\x1b\n" +
	"\tcamera_id\x18\x04 \x01(\tR\bcameraId\x12\x1b\n" +
	"\tminio_key\x18\x05 \x01(\tR\bminioKey\x12-\n" +
	"\x13captured_at_unix_ns\x18\x06 \x01(\x06R\x10capturedAtUnixNs\x12?\n" +
	"\n" +
	"tag_reason\x18\a \x01(\x0e2 .continuoustracking.v1.TagReasonR\ttagReason\x12)\n" +
	"\x10annotations_json\x18\b \x01(\tR\x0fannotationsJson\x12+\n" +
	"\x12expires_at_unix_ns\x18\t \x01(\x06R\x0fexpiresAtUnixNs*\xc9\x01\n" +
	"\tTagReason\x12\x1a\n" +
	"\x16TAG_REASON_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13TAG_REASON_PERIODIC\x10\x01\x12\x1f\n" +
	"\x1bTAG_REASON_IDENTITY_CHANGED\x10\x02\x12\x15\n" +
	"\x11TAG_REASON_HAZARD\x10\x03\x12\x1a\n" +
	"\x16TAG_REASON_DWELL_START\x10\x04\x12\x13\n" +
	"\x0fTAG_REASON_FALL\x10\x05\x12\x1e\n" +
	"\x1aTAG_REASON_DEMENTIA_SIGNAL\x10\x06BDZBgithub.com/khoofia/continuous-tracking/proto/continuoustracking/v1b\x06proto3"

var (
	file_continuoustracking_v1_scene_proto_rawDescOnce sync.Once
	file_continuoustracking_v1_scene_proto_rawDescData []byte
)

func file_continuoustracking_v1_scene_proto_rawDescGZIP() []byte {
	file_continuoustracking_v1_scene_proto_rawDescOnce.Do(func() {
		file_continuoustracking_v1_scene_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_continuoustracking_v1_scene_proto_rawDesc), len(file_continuoustracking_v1_scene_proto_rawDesc)))
	})
	return file_continuoustracking_v1_scene_proto_rawDescData
}

var file_continuoustracking_v1_scene_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_continuoustracking_v1_scene_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_continuoustracking_v1_scene_proto_goTypes = []any{
	(TagReason)(0),      // 0: continuoustracking.v1.TagReason
	(*SceneSample)(nil), // 1: continuoustracking.v1.SceneSample
}
var file_continuoustracking_v1_scene_proto_depIdxs = []int32{
	0, // 0: continuoustracking.v1.SceneSample.tag_reason:type_name -> continuoustracking.v1.TagReason
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_continuoustracking_v1_scene_proto_init() }
func file_continuoustracking_v1_scene_proto_init() {
	if File_continuoustracking_v1_scene_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_continuoustracking_v1_scene_proto_rawDesc), len(file_continuoustracking_v1_scene_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_continuoustracking_v1_scene_proto_goTypes,
		DependencyIndexes: file_continuoustracking_v1_scene_proto_depIdxs,
		EnumInfos:         file_continuoustracking_v1_scene_proto_enumTypes,
		MessageInfos:      file_continuoustracking_v1_scene_proto_msgTypes,
	}.Build()
	File_continuoustracking_v1_scene_proto = out.File
	file_continuoustracking_v1_scene_proto_goTypes = nil
	file_continuoustracking_v1_scene_proto_depIdxs = nil
}
