// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: continuoustracking/v1/signals.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DementiaSignalKind int32

const (
	DementiaSignalKind_DEMENTIA_SIGNAL_KIND_UNSPECIFIED            DementiaSignalKind = 0
	DementiaSignalKind_DEMENTIA_SIGNAL_KIND_PACING                 DementiaSignalKind = 1
	DementiaSignalKind_DEMENTIA_SIGNAL_KIND_SUNDOWNING_INDEX       DementiaSignalKind = 2
	DementiaSignalKind_DEMENTIA_SIGNAL_KIND_BATHROOM_DWELL_ANOMALY DementiaSignalKind = 3
	DementiaSignalKind_DEMENTIA_SIGNAL_KIND_NIGHTTIME_MOVEMENT     DementiaSignalKind = 4
	DementiaSignalKind_DEMENTIA_SIGNAL_KIND_STILLNESS_ANOMALY      DementiaSignalKind = 5
	DementiaSignalKind_DEMENTIA_SIGNAL_KIND_ABSENCE                DementiaSignalKind = 6
)

// Enum value maps for DementiaSignalKind.
var (
	DementiaSignalKind_name = map[int32]string{
		0: "DEMENTIA_SIGNAL_KIND_UNSPECIFIED",
		1: "DEMENTIA_SIGNAL_KIND_PACING",
		2: "DEMENTIA_SIGNAL_KIND_SUNDOWNING_INDEX",
		3: "DEMENTIA_SIGNAL_KIND_BATHROOM_DWELL_ANOMALY",
		4: "DEMENTIA_SIGNAL_KIND_NIGHTTIME_MOVEMENT",
		5: "DEMENTIA_SIGNAL_KIND_STILLNESS_ANOMALY",
		6: "DEMENTIA_SIGNAL_KIND_ABSENCE",
	}
	DementiaSignalKind_value = map[string]int32{
		"DEMENTIA_SIGNAL_KIND_UNSPECIFIED":            0,
		"DEMENTIA_SIGNAL_KIND_PACING":                 1,
		"DEMENTIA_SIGNAL_KIND_SUNDOWNING_INDEX":       2,
		"DEMENTIA_SIGNAL_KIND_BATHROOM_DWELL_ANOMALY": 3,
		"DEMENTIA_SIGNAL_KIND_NIGHTTIME_MOVEMENT":     4,
		"DEMENTIA_SIGNAL_KIND_STILLNESS_ANOMALY":      5,
		"DEMENTIA_SIGNAL_KIND_ABSENCE":                6,
	}
)

func (x DementiaSignalKind) Enum() *DementiaSignalKind {
	p := new(DementiaSignalKind)
	*p = x
	return p
}

func (x DementiaSignalKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DementiaSignalKind) Descriptor() protoreflect.EnumDescriptor {
	return file_continuoustracking_v1_signals_proto_enumTypes[0].Descriptor()
}

func (DementiaSignalKind) Type() protoreflect.EnumType {
	return &file_continuoustracking_v1_signals_proto_enumTypes[0]
}

func (x DementiaSignalKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DementiaSignalKind.Descriptor instead.
func (DementiaSignalKind) EnumDescriptor() ([]byte, []int) {
	return file_continuoustracking_v1_signals_proto_rawDescGZIP(), []int{0}
}

type DementiaSignalSeverity int32

const (
	DementiaSignalSeverity_DEMENTIA_SIGNAL_SEVERITY_UNSPECIFIED DementiaSignalSeverity = 0
	DementiaSignalSeverity_DEMENTIA_SIGNAL_SEVERITY_INFO        DementiaSignalSeverity = 1
	DementiaSignalSeverity_DEMENTIA_SIGNAL_SEVERITY_WARNING     DementiaSignalSeverity = 2
	DementiaSignalSeverity_DEMENTIA_SIGNAL_SEVERITY_EMERGENCY   DementiaSignalSeverity = 3
)

// Enum value maps for DementiaSignalSeverity.
var (
	DementiaSignalSeverity_name = map[int32]string{
		0: "DEMENTIA_SIGNAL_SEVERITY_UNSPECIFIED",
		1: "DEMENTIA_SIGNAL_SEVERITY_INFO",
		2: "DEMENTIA_SIGNAL_SEVERITY_WARNING",
		3: "DEMENTIA_SIGNAL_SEVERITY_EMERGENCY",
	}
	DementiaSignalSeverity_value = map[string]int32{
		"DEMENTIA_SIGNAL_SEVERITY_UNSPECIFIED": 0,
		"DEMENTIA_SIGNAL_SEVERITY_INFO":        1,
		"DEMENTIA_SIGNAL_SEVERITY_WARNING":     2,
		"DEMENTIA_SIGNAL_SEVERITY_EMERGENCY":   3,
	}
)

func (x DementiaSignalSeverity) Enum() *DementiaSignalSeverity {
	p := new(DementiaSignalSeverity)
	*p = x
	return p
}

func (x DementiaSignalSeverity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DementiaSignalSeverity) Descriptor() protoreflect.EnumDescriptor {
	return file_continuoustracking_v1_signals_proto_enumTypes[1].Descriptor()
}

func (DementiaSignalSeverity) Type() protoreflect.EnumType {
	return &file_continuoustracking_v1_signals_proto_enumTypes[1]
}

func (x DementiaSignalSeverity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DementiaSignalSeverity.Descriptor instead.
func (DementiaSignalSeverity) EnumDescriptor() ([]byte, []int) {
	return file_continuoustracking_v1_signals_proto_rawDescGZIP(), []int{1}
}

// DementiaSignal is published to the tracking.signals Redis Stream by the
// orchestrator's DementiaSignalWorker after each evaluation window.
// Cognitive Companion's DementiaSignalSubscriber persists each signal and
// fires a context filter so caregiver rules can react.
type DementiaSignal struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique stable signal ID. Computed deterministically from
	// (identity_id, kind, window_start, window_end) so a re-emission of the
	// same window is idempotent on the consumer side.
	SignalId string `protobuf:"bytes,1,opt,name=signal_id,json=signalId,proto3" json:"signal_id,omitempty"`
	// Resident the signal is about.
	IdentityId string                 `protobuf:"bytes,2,opt,name=identity_id,json=identityId,proto3" json:"identity_id,omitempty"`
	Kind       DementiaSignalKind     `protobuf:"varint,3,opt,name=kind,proto3,enum=continuoustracking.v1.DementiaSignalKind" json:"kind,omitempty"`
	Severity   DementiaSignalSeverity `protobuf:"varint,4,opt,name=severity,proto3,enum=continuoustracking.v1.DementiaSignalSeverity" json:"severity,omitempty"`
	// Raw value of the signal in its natural units (steps, minutes, etc).
	Value float32 `protobuf:"fixed32,5,opt,name=value,proto3" json:"value,omitempty"`
	// Per-resident historical baseline. Optional; encoded via has_baseline.
	HasBaseline bool    `protobuf:"varint,6,opt,name=has_baseline,json=hasBaseline,proto3" json:"has_baseline,omitempty"`
	Baseline    float32 `protobuf:"fixed32,7,opt,name=baseline,proto3" json:"baseline,omitempty"`
	// z-score relative to the baseline distribution. Optional.
	HasZScore bool    `protobuf:"varint,8,opt,name=has_z_score,json=hasZScore,proto3" json:"has_z_score,omitempty"`
	ZScore    float32 `protobuf:"fixed32,9,opt,name=z_score,json=zScore,proto3" json:"z_score,omitempty"`
	// Window the signal was computed over.
	WindowStartUnixNs uint64 `protobuf:"fixed64,10,opt,name=window_start_unix_ns,json=windowStartUnixNs,proto3" json:"window_start_unix_ns,omitempty"`
	WindowEndUnixNs   uint64 `protobuf:"fixed64,11,opt,name=window_end_unix_ns,json=windowEndUnixNs,proto3" json:"window_end_unix_ns,omitempty"`
	// When the worker emitted the signal (wall clock).
	EmittedAtUnixNs uint64 `protobuf:"fixed64,12,opt,name=emitted_at_unix_ns,json=emittedAtUnixNs,proto3" json:"emitted_at_unix_ns,omitempty"`
	// Detector-specific context (window count, room name, last-known posture,
	// etc.) serialised as a JSON string. Free-form by design.
	ContextJson string `protobuf:"bytes,13,opt,name=context_json,json=contextJson,proto3" json:"context_json,omitempty"`
	// Monotonically incremented detector algorithm version.  A bump indicates
	// the semantics of value/baseline/z_score may have changed.  Consumers
	// should use this to filter stale-version signals out of "active" rollups.
	AlgorithmVersion int32 `protobuf:"varint,14,opt,name=algorithm_version,json=algorithmVersion,proto3" json:"algorithm_version,omitempty"`
	// Human-readable algorithm name for clinical documentation.
	AlgorithmName string `protobuf:"bytes,15,opt,name=algorithm_name,json=algorithmName,proto3" json:"algorithm_name,omitempty"`
	// Evidence grade for clinical signal interpretation:
	// clinical_review | observational_study | caregiver_guidance |
	// local_baseline_only | experimental
	EvidenceGrade string `protobuf:"bytes,16,opt,name=evidence_grade,json=evidenceGrade,proto3" json:"evidence_grade,omitempty"`
	// JSON-serialized algorithm specification including thresholds,
	// window sizes, and detector hyperparameters.
	AlgorithmSpecJson string `protobuf:"bytes,17,opt,name=algorithm_spec_json,json=algorithmSpecJson,proto3" json:"algorithm_spec_json,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DementiaSignal) Reset() {
	*x = DementiaSignal{}
	mi := &file_continuoustracking_v1_signals_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DementiaSignal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DementiaSignal) ProtoMessage() {}

func (x *DementiaSignal) ProtoReflect() protoreflect.Message {
	mi := &file_continuoustracking_v1_signals_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DementiaSignal.ProtoReflect.Descriptor instead.
func (*DementiaSignal) Descriptor() ([]byte, []int) {
	return file_continuoustracking_v1_signals_proto_rawDescGZIP(), []int{0}
}

func (x *DementiaSignal) GetSignalId() string {
	if x != nil {
		return x.SignalId
	}
	return ""
}

func (x *DementiaSignal) GetIdentityId() string {
	if x != nil {
		return x.IdentityId
	}
	return ""
}

func (x *DementiaSignal) GetKind() DementiaSignalKind {
	if x != nil {
		return x.Kind
	}
	return DementiaSignalKind_DEMENTIA_SIGNAL_KIND_UNSPECIFIED
}

func (x *DementiaSignal) GetSeverity() DementiaSignalSeverity {
	if x != nil {
		return x.Severity
	}
	return DementiaSignalSeverity_DEMENTIA_SIGNAL_SEVERITY_UNSPECIFIED
}

func (x *DementiaSignal) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *DementiaSignal) GetHasBaseline() bool {
	if x != nil {
		return x.HasBaseline
	}
	return false
}

func (x *DementiaSignal) GetBaseline() float32 {
	if x != nil {
		return x.Baseline
	}
	return 0
}

func (x *DementiaSignal) GetHasZScore() bool {
	if x != nil {
		return x.HasZScore
	}
	return false
}

func (x *DementiaSignal) GetZScore() float32 {
	if x != nil {
		return x.ZScore
	}
	return 0
}

func (x *DementiaSignal) GetWindowStartUnixNs() uint64 {
	if x != nil {
		return x.WindowStartUnixNs
	}
	return 0
}

func (x *DementiaSignal) GetWindowEndUnixNs() uint64 {
	if x != nil {
		return x.WindowEndUnixNs
	}
	return 0
}

func (x *DementiaSignal) GetEmittedAtUnixNs() uint64 {
	if x != nil {
		return x.EmittedAtUnixNs
	}
	return 0
}

func (x *DementiaSignal) GetContextJson() string {
	if x != nil {
		return x.ContextJson
	}
	return ""
}

func (x *DementiaSignal) GetAlgorithmVersion() int32 {
	if x != nil {
		return x.AlgorithmVersion
	}
	return 0
}

func (x *DementiaSignal) GetAlgorithmName() string {
	if x != nil {
		return x.AlgorithmName
	}
	return ""
}

func (x *DementiaSignal) GetEvidenceGrade() string {
	if x != nil {
		return x.EvidenceGrade
	}
	return ""
}

func (x *DementiaSignal) GetAlgorithmSpecJson() string {
	if x != nil {
		return x.AlgorithmSpecJson
	}
	return ""
}

var File_continuoustracking_v1_signals_proto protoreflect.FileDescriptor

const file_continuoustracking_v1_signals_proto_rawDesc = "" +
	"\n" +
	"#continuoustracking/v1/signals.proto\x12\x15continuoustracking.v1\"\xbf\x05\n" +
	"\x0eDementiaSignal\x12\x1b\n" +
	"\tsignal_id\x18\x01 \x01(\tR\bsignalId\x12\x1f\n" +
	"\videntity_id\x18\x02 \x01(\tR\n" +
	"identityId\x12=\n" +
	"\x04kind\x18\x03 \x01(\x0e2).continuoustracking.v1.DementiaSignalKindR\x04kind\x12I\n" +
	"\bseverity\x18\x04 \x01(\x0e2-.continuoustracking.v1.DementiaSignalSeverityR\bseverity\x12\x14\n" +
	"\x05value\x18\x05 \x01(\x02R\x05value\x12!\n" +
	"\fhas_baseline\x18\x06 \x01(\bR\vhasBaseline\x12\x1a\n" +
	"\bbaseline\x18\a \x01(\x02R\bbaseline\x12\x1e\n" +
	"\vhas_z_score\x18\b \x01(\bR\thasZScore\x12\x17\n" +
	"\az_score\x18\t \x01(\x02R\x06zScore\x12/\n" +
	"\x14window_start_unix_ns\x18\n" +
	" \x01(\x06R\x11windowStartUnixNs\x12+\n" +
	"\x12window_end_unix_ns\x18\v \x01(\x06R\x0fwindowEndUnixNs\x12+\n" +
	"\x12emitted_at_unix_ns\x18\f \x01(\x06R\x0femittedAtUnixNs\x12!\n" +
	"\fcontext_json\x18\r \x01(\tR\vcontextJson\x12+\n" +
	"\x11algorithm_version\x18\x0e \x01(\x05R\x10algorithmVersion\x12%\n" +
	"\x0ealgorithm_name\x18\x0f \x01(\tR\ralgorithmName\x12%\n" +
	"\x0eevidence_grade\x18\x10 \x01(\tR\revidenceGrade\x12.\n" +
	"\x13algorithm_spec_json\x18\x11 \x01(\tR\x11algorithmSpecJson*\xb2\x02\n" +
	"\x12DementiaSignalKind\x12$\n" +
	" DEMENTIA_SIGNAL_KIND_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bDEMENTIA_SIGNAL_KIND_PACING\x10\x01\x12)\n" +
	"%DEMENTIA_SIGNAL_KIND_SUNDOWNING_INDEX\x10\x02\x12/\n" +
	"+DEMENTIA_SIGNAL_KIND_BATHROOM_DWELL_ANOMALY\x10\x03\x12+\n" +
	"'DEMENTIA_SIGNAL_KIND_NIGHTTIME_MOVEMENT\x10\x04\x12*\n" +
	"&DEMENTIA_SIGNAL_KIND_STILLNESS_ANOMALY\x10\x05\x12 \n" +
	"\x1cDEMENTIA_SIGNAL_KIND_ABSENCE\x10\x06*\xb3\x01\n" +
	"\x16DementiaSignalSeverity\x12(\n" +
	"$DEMENTIA_SIGNAL_SEVERITY_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dDEMENTIA_SIGNAL_SEVERITY_INFO\x10\x01\x12$\n" +
	" DEMENTIA_SIGNAL_SEVERITY_WARNING\x10\x02\x12&\n" +
	"\"DEMENTIA_SIGNAL_SEVERITY_EMERGENCY\x10\x03BOZMgithub.com/SilverMind-Project/continuous-tracking/proto/continuoustracking/v1b\x06proto3"

var (
	file_continuoustracking_v1_signals_proto_rawDescOnce sync.Once
	file_continuoustracking_v1_signals_proto_rawDescData []byte
)

func file_continuoustracking_v1_signals_proto_rawDescGZIP() []byte {
	file_continuoustracking_v1_signals_proto_rawDescOnce.Do(func() {
		file_continuoustracking_v1_signals_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_continuoustracking_v1_signals_proto_rawDesc), len(file_continuoustracking_v1_signals_proto_rawDesc)))
	})
	return file_continuoustracking_v1_signals_proto_rawDescData
}

var file_continuoustracking_v1_signals_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_continuoustracking_v1_signals_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_continuoustracking_v1_signals_proto_goTypes = []any{
	(DementiaSignalKind)(0),     // 0: continuoustracking.v1.DementiaSignalKind
	(DementiaSignalSeverity)(0), // 1: continuoustracking.v1.DementiaSignalSeverity
	(*DementiaSignal)(nil),      // 2: continuoustracking.v1.DementiaSignal
}
var file_continuoustracking_v1_signals_proto_depIdxs = []int32{
	0, // 0: continuoustracking.v1.DementiaSignal.kind:type_name -> continuoustracking.v1.DementiaSignalKind
	1, // 1: continuoustracking.v1.DementiaSignal.severity:type_name -> continuoustracking.v1.DementiaSignalSeverity
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_continuoustracking_v1_signals_proto_init() }
func file_continuoustracking_v1_signals_proto_init() {
	if File_continuoustracking_v1_signals_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_continuoustracking_v1_signals_proto_rawDesc), len(file_continuoustracking_v1_signals_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_continuoustracking_v1_signals_proto_goTypes,
		DependencyIndexes: file_continuoustracking_v1_signals_proto_depIdxs,
		EnumInfos:         file_continuoustracking_v1_signals_proto_enumTypes,
		MessageInfos:      file_continuoustracking_v1_signals_proto_msgTypes,
	}.Build()
	File_continuoustracking_v1_signals_proto = out.File
	file_continuoustracking_v1_signals_proto_goTypes = nil
	file_continuoustracking_v1_signals_proto_depIdxs = nil
}
