// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: continuoustracking/v1/tracking.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TrackingEvent is the core message produced by the tracking-orchestrator
// after processing a frame. It carries the Bayesian identity posterior,
// spatial coordinates, and temporal metadata.
type TrackingEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identity of the camera stream (matches RTSP ingress config).
	CameraId string `protobuf:"bytes,1,opt,name=camera_id,json=cameraId,proto3" json:"camera_id,omitempty"`
	// Wall-clock time when the event was committed (not when frame arrived).
	// Used as the authoritative timestamp for ordering.
	EventTimeUnixNs uint64 `protobuf:"fixed64,2,opt,name=event_time_unix_ns,json=eventTimeUnixNs,proto3" json:"event_time_unix_ns,omitempty"`
	// Frame-level metadata.
	FrameRef *FrameRef `protobuf:"bytes,3,opt,name=frame_ref,json=frameRef,proto3" json:"frame_ref,omitempty"`
	// One entry per detected person in the frame.
	Detections []*Detection `protobuf:"bytes,4,rep,name=detections,proto3" json:"detections,omitempty"`
	// Identity resolution: for each global track that was matched to a known
	// person, the posterior probability distribution over candidates.
	IdentityRevisions []*IdentityRevision `protobuf:"bytes,5,rep,name=identity_revisions,json=identityRevisions,proto3" json:"identity_revisions,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TrackingEvent) Reset() {
	*x = TrackingEvent{}
	mi := &file_continuoustracking_v1_tracking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackingEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackingEvent) ProtoMessage() {}

func (x *TrackingEvent) ProtoReflect() protoreflect.Message {
	mi := &file_continuoustracking_v1_tracking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackingEvent.ProtoReflect.Descriptor instead.
func (*TrackingEvent) Descriptor() ([]byte, []int) {
	return file_continuoustracking_v1_tracking_proto_rawDescGZIP(), []int{0}
}

func (x *TrackingEvent) GetCameraId() string {
	if x != nil {
		return x.CameraId
	}
	return ""
}

func (x *TrackingEvent) GetEventTimeUnixNs() uint64 {
	if x != nil {
		return x.EventTimeUnixNs
	}
	return 0
}

func (x *TrackingEvent) GetFrameRef() *FrameRef {
	if x != nil {
		return x.FrameRef
	}
	return nil
}

func (x *TrackingEvent) GetDetections() []*Detection {
	if x != nil {
		return x.Detections
	}
	return nil
}

func (x *TrackingEvent) GetIdentityRevisions() []*IdentityRevision {
	if x != nil {
		return x.IdentityRevisions
	}
	return nil
}

// FrameRef points to a frame stored in MinIO without duplicating pixel data.
type FrameRef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// MinIO object key for the original frame.
	MinioKey string `protobuf:"bytes,1,opt,name=minio_key,json=minioKey,proto3" json:"minio_key,omitempty"`
	// Frame resolution.
	Width  int32 `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height int32 `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	// Frame index within the camera stream (monotonically increasing).
	FrameIndex int64 `protobuf:"varint,4,opt,name=frame_index,json=frameIndex,proto3" json:"frame_index,omitempty"`
	// Capture time from the RTSP source (pre-NTP correction).
	CaptureTimeUnixNs uint64 `protobuf:"fixed64,5,opt,name=capture_time_unix_ns,json=captureTimeUnixNs,proto3" json:"capture_time_unix_ns,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *FrameRef) Reset() {
	*x = FrameRef{}
	mi := &file_continuoustracking_v1_tracking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrameRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameRef) ProtoMessage() {}

func (x *FrameRef) ProtoReflect() protoreflect.Message {
	mi := &file_continuoustracking_v1_tracking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameRef.ProtoReflect.Descriptor instead.
func (*FrameRef) Descriptor() ([]byte, []int) {
	return file_continuoustracking_v1_tracking_proto_rawDescGZIP(), []int{1}
}

func (x *FrameRef) GetMinioKey() string {
	if x != nil {
		return x.MinioKey
	}
	return ""
}

func (x *FrameRef) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *FrameRef) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *FrameRef) GetFrameIndex() int64 {
	if x != nil {
		return x.FrameIndex
	}
	return 0
}

func (x *FrameRef) GetCaptureTimeUnixNs() uint64 {
	if x != nil {
		return x.CaptureTimeUnixNs
	}
	return 0
}

// Detection represents one person detected in a single frame.
type Detection struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique per-frame identifier for this detection bounding box.
	DetectionId string `protobuf:"bytes,1,opt,name=detection_id,json=detectionId,proto3" json:"detection_id,omitempty"`
	// Bounding box in pixel coordinates (top-left origin).
	Bbox *BoundingBox `protobuf:"bytes,2,opt,name=bbox,proto3" json:"bbox,omitempty"`
	// Embedding vector from the ReID model (L2-normalized, float32).
	// The canonical production model is SOLIDER-REID with 768 dimensions.
	Embedding []float32 `protobuf:"fixed32,3,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	// Confidence score from the detection model (0.0 to 1.0).
	Confidence float32 `protobuf:"fixed32,4,opt,name=confidence,proto3" json:"confidence,omitempty"`
	// Tracklet this detection belongs to (assigned by tracking logic).
	TrackletId string `protobuf:"bytes,5,opt,name=tracklet_id,json=trackletId,proto3" json:"tracklet_id,omitempty"`
	// Global track ID if already resolved to a known person.
	// Empty until the first match is made.
	GlobalTrackId string `protobuf:"bytes,6,opt,name=global_track_id,json=globalTrackId,proto3" json:"global_track_id,omitempty"`
	// Floor point (x, y) in millimeters relative to the camera's calibrated
	// coordinate system. Origin is the camera's ground intersection point.
	FloorPoint    *FloorPoint `protobuf:"bytes,7,opt,name=floor_point,json=floorPoint,proto3" json:"floor_point,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Detection) Reset() {
	*x = Detection{}
	mi := &file_continuoustracking_v1_tracking_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Detection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Detection) ProtoMessage() {}

func (x *Detection) ProtoReflect() protoreflect.Message {
	mi := &file_continuoustracking_v1_tracking_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Detection.ProtoReflect.Descriptor instead.
func (*Detection) Descriptor() ([]byte, []int) {
	return file_continuoustracking_v1_tracking_proto_rawDescGZIP(), []int{2}
}

func (x *Detection) GetDetectionId() string {
	if x != nil {
		return x.DetectionId
	}
	return ""
}

func (x *Detection) GetBbox() *BoundingBox {
	if x != nil {
		return x.Bbox
	}
	return nil
}

func (x *Detection) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

func (x *Detection) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Detection) GetTrackletId() string {
	if x != nil {
		return x.TrackletId
	}
	return ""
}

func (x *Detection) GetGlobalTrackId() string {
	if x != nil {
		return x.GlobalTrackId
	}
	return ""
}

func (x *Detection) GetFloorPoint() *FloorPoint {
	if x != nil {
		return x.FloorPoint
	}
	return nil
}

// BoundingBox in pixel coordinates: top-left origin, width/height positive.
type BoundingBox struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	XMin          int32                  `protobuf:"varint,1,opt,name=x_min,json=xMin,proto3" json:"x_min,omitempty"`
	YMin          int32                  `protobuf:"varint,2,opt,name=y_min,json=yMin,proto3" json:"y_min,omitempty"`
	XMax          int32                  `protobuf:"varint,3,opt,name=x_max,json=xMax,proto3" json:"x_max,omitempty"`
	YMax          int32                  `protobuf:"varint,4,opt,name=y_max,json=yMax,proto3" json:"y_max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoundingBox) Reset() {
	*x = BoundingBox{}
	mi := &file_continuoustracking_v1_tracking_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoundingBox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoundingBox) ProtoMessage() {}

func (x *BoundingBox) ProtoReflect() protoreflect.Message {
	mi := &file_continuoustracking_v1_tracking_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoundingBox.ProtoReflect.Descriptor instead.
func (*BoundingBox) Descriptor() ([]byte, []int) {
	return file_continuoustracking_v1_tracking_proto_rawDescGZIP(), []int{3}
}

func (x *BoundingBox) GetXMin() int32 {
	if x != nil {
		return x.XMin
	}
	return 0
}

func (x *BoundingBox) GetYMin() int32 {
	if x != nil {
		return x.YMin
	}
	return 0
}

func (x *BoundingBox) GetXMax() int32 {
	if x != nil {
		return x.XMax
	}
	return 0
}

func (x *BoundingBox) GetYMax() int32 {
	if x != nil {
		return x.YMax
	}
	return 0
}

// FloorPoint is a 2D point on the ground plane, in millimeters.
type FloorPoint struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// X coordinate in mm from camera origin.
	XMm int64 `protobuf:"varint,1,opt,name=x_mm,json=xMm,proto3" json:"x_mm,omitempty"`
	// Y coordinate in mm from camera origin.
	YMm int64 `protobuf:"varint,2,opt,name=y_mm,json=yMm,proto3" json:"y_mm,omitempty"`
	// Whether the point was computed (true) or is a projection (false).
	Calibrated    bool `protobuf:"varint,3,opt,name=calibrated,proto3" json:"calibrated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FloorPoint) Reset() {
	*x = FloorPoint{}
	mi := &file_continuoustracking_v1_tracking_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FloorPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FloorPoint) ProtoMessage() {}

func (x *FloorPoint) ProtoReflect() protoreflect.Message {
	mi := &file_continuoustracking_v1_tracking_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FloorPoint.ProtoReflect.Descriptor instead.
func (*FloorPoint) Descriptor() ([]byte, []int) {
	return file_continuoustracking_v1_tracking_proto_rawDescGZIP(), []int{4}
}

func (x *FloorPoint) GetXMm() int64 {
	if x != nil {
		return x.XMm
	}
	return 0
}

func (x *FloorPoint) GetYMm() int64 {
	if x != nil {
		return x.YMm
	}
	return 0
}

func (x *FloorPoint) GetCalibrated() bool {
	if x != nil {
		return x.Calibrated
	}
	return false
}

// IdentityRevision captures the Bayesian posterior update for a single
// global track at a given event time.
type IdentityRevision struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The global track being updated.
	GlobalTrackId string `protobuf:"bytes,1,opt,name=global_track_id,json=globalTrackId,proto3" json:"global_track_id,omitempty"`
	// Probability distribution over candidate identities.
	Candidates []*IdentityCandidate `protobuf:"bytes,2,rep,name=candidates,proto3" json:"candidates,omitempty"`
	// The MAP (maximum a posteriori) estimate.
	MapIdentityId string `protobuf:"bytes,3,opt,name=map_identity_id,json=mapIdentityId,proto3" json:"map_identity_id,omitempty"`
	// Entropy of the posterior (measure of uncertainty, in nats).
	// Lower = more certain. Used by the dementia layer for confidence gating.
	PosteriorEntropy float32 `protobuf:"fixed32,4,opt,name=posterior_entropy,json=posteriorEntropy,proto3" json:"posterior_entropy,omitempty"`
	// When this revision was computed.
	RevisionTimeUnixNs uint64 `protobuf:"fixed64,5,opt,name=revision_time_unix_ns,json=revisionTimeUnixNs,proto3" json:"revision_time_unix_ns,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *IdentityRevision) Reset() {
	*x = IdentityRevision{}
	mi := &file_continuoustracking_v1_tracking_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityRevision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityRevision) ProtoMessage() {}

func (x *IdentityRevision) ProtoReflect() protoreflect.Message {
	mi := &file_continuoustracking_v1_tracking_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityRevision.ProtoReflect.Descriptor instead.
func (*IdentityRevision) Descriptor() ([]byte, []int) {
	return file_continuoustracking_v1_tracking_proto_rawDescGZIP(), []int{5}
}

func (x *IdentityRevision) GetGlobalTrackId() string {
	if x != nil {
		return x.GlobalTrackId
	}
	return ""
}

func (x *IdentityRevision) GetCandidates() []*IdentityCandidate {
	if x != nil {
		return x.Candidates
	}
	return nil
}

func (x *IdentityRevision) GetMapIdentityId() string {
	if x != nil {
		return x.MapIdentityId
	}
	return ""
}

func (x *IdentityRevision) GetPosteriorEntropy() float32 {
	if x != nil {
		return x.PosteriorEntropy
	}
	return 0
}

func (x *IdentityRevision) GetRevisionTimeUnixNs() uint64 {
	if x != nil {
		return x.RevisionTimeUnixNs
	}
	return 0
}

// IdentityCandidate is one candidate identity with its posterior probability.
type IdentityCandidate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The identity's gallery entry ID.
	IdentityId string `protobuf:"bytes,1,opt,name=identity_id,json=identityId,proto3" json:"identity_id,omitempty"`
	// Display name for the identity.
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Posterior probability P(identity | observations).
	Probability   float32 `protobuf:"fixed32,3,opt,name=probability,proto3" json:"probability,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentityCandidate) Reset() {
	*x = IdentityCandidate{}
	mi := &file_continuoustracking_v1_tracking_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityCandidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityCandidate) ProtoMessage() {}

func (x *IdentityCandidate) ProtoReflect() protoreflect.Message {
	mi := &file_continuoustracking_v1_tracking_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityCandidate.ProtoReflect.Descriptor instead.
func (*IdentityCandidate) Descriptor() ([]byte, []int) {
	return file_continuoustracking_v1_tracking_proto_rawDescGZIP(), []int{6}
}

func (x *IdentityCandidate) GetIdentityId() string {
	if x != nil {
		return x.IdentityId
	}
	return ""
}

func (x *IdentityCandidate) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *IdentityCandidate) GetProbability() float32 {
	if x != nil {
		return x.Probability
	}
	return 0
}

var File_continuoustracking_v1_tracking_proto protoreflect.FileDescriptor

const file_continuoustracking_v1_tracking_proto_rawDesc = "" +
	"\n" +
	"$continuoustracking/v1/tracking.proto\x12\x15continuoustracking.v1\"\xb1\x02\n" +
	"\rTrackingEvent\x12\x1b\n" +
	"\tcamera_id\x18\x01 \x01(\tR\bcameraId\x12+\n" +
	"\x12event_time_unix_ns\x18\x02 \x01(\x06R\x0feventTimeUnixNs\x12<\n" +
	"\tframe_ref\x18\x03 \x01(\v2\x1f.continuoustracking.v1.FrameRefR\bframeRef\x12@\n" +
	"\n" +
	"detections\x18\x04 \x03(\v2 .continuoustracking.v1.DetectionR\n" +
	"detections\x12V\n" +
	"\x12identity_revisions\x18\x05 \x03(\v2'.continuoustracking.v1.IdentityRevisionR\x11identityRevisions\"\xa7\x01\n" +
	"\bFrameRef\x12\x1b\n" +
	"\tminio_key\x18\x01 \x01(\tR\bminioKey\x12\x14\n" +
	"\x05width\x18\x02 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x05R\x06height\x12\x1f\n" +
	"\vframe_index\x18\x04 \x01(\x03R\n" +
	"frameIndex\x12/\n" +
	"\x14capture_time_unix_ns\x18\x05 \x01(\x06R\x11captureTimeUnixNs\"\xb1\x02\n" +
	"\tDetection\x12!\n" +
	"\fdetection_id\x18\x01 \x01(\tR\vdetectionId\x126\n" +
	"\x04bbox\x18\x02 \x01(\v2\".continuoustracking.v1.BoundingBoxR\x04bbox\x12\x1c\n" +
	"\tembedding\x18\x03 \x03(\x02R\tembedding\x12\x1e\n" +
	"\n" +
	"confidence\x18\x04 \x01(\x02R\n" +
	"confidence\x12\x1f\n" +
	"\vtracklet_id\x18\x05 \x01(\tR\n" +
	"trackletId\x12&\n" +
	"\x0fglobal_track_id\x18\x06 \x01(\tR\rglobalTrackId\x12B\n" +
	"\vfloor_point\x18\a \x01(\v2!.continuoustracking.v1.FloorPointR\n" +
	"floorPoint\"a\n" +
	"\vBoundingBox\x12\x13\n" +
	"\x05x_min\x18\x01 \x01(\x05R\x04xMin\x12\x13\n" +
	"\x05y_min\x18\x02 \x01(\x05R\x04yMin\x12\x13\n" +
	"\x05x_max\x18\x03 \x01(\x05R\x04xMax\x12\x13\n" +
	"\x05y_max\x18\x04 \x01(\x05R\x04yMax\"R\n" +
	"\n" +
	"FloorPoint\x12\x11\n" +
	"\x04x_mm\x18\x01 \x01(\x03R\x03xMm\x12\x11\n" +
	"\x04y_mm\x18\x02 \x01(\x03R\x03yMm\x12\x1e\n" +
	"\n" +
	"calibrated\x18\x03 \x01(\bR\n" +
	"calibrated\"\x8c\x02\n" +
	"\x10IdentityRevision\x12&\n" +
	"\x0fglobal_track_id\x18\x01 \x01(\tR\rglobalTrackId\x12H\n" +
	"\n" +
	"candidates\x18\x02 \x03(\v2(.continuoustracking.v1.IdentityCandidateR\n" +
	"candidates\x12&\n" +
	"\x0fmap_identity_id\x18\x03 \x01(\tR\rmapIdentityId\x12+\n" +
	"\x11posterior_entropy\x18\x04 \x01(\x02R\x10posteriorEntropy\x121\n" +
	"\x15revision_time_unix_ns\x18\x05 \x01(\x06R\x12revisionTimeUnixNs\"y\n" +
	"\x11IdentityCandidate\x12\x1f\n" +
	"\videntity_id\x18\x01 \x01(\tR\n" +
	"identityId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12 \n" +
	"\vprobability\x18\x03 \x01(\x02R\vprobabilityBDZBgithub.com/khoofia/continuous-tracking/proto/continuoustracking/v1b\x06proto3"

var (
	file_continuoustracking_v1_tracking_proto_rawDescOnce sync.Once
	file_continuoustracking_v1_tracking_proto_rawDescData []byte
)

func file_continuoustracking_v1_tracking_proto_rawDescGZIP() []byte {
	file_continuoustracking_v1_tracking_proto_rawDescOnce.Do(func() {
		file_continuoustracking_v1_tracking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_continuoustracking_v1_tracking_proto_rawDesc), len(file_continuoustracking_v1_tracking_proto_rawDesc)))
	})
	return file_continuoustracking_v1_tracking_proto_rawDescData
}

var file_continuoustracking_v1_tracking_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_continuoustracking_v1_tracking_proto_goTypes = []any{
	(*TrackingEvent)(nil),     // 0: continuoustracking.v1.TrackingEvent
	(*FrameRef)(nil),          // 1: continuoustracking.v1.FrameRef
	(*Detection)(nil),         // 2: continuoustracking.v1.Detection
	(*BoundingBox)(nil),       // 3: continuoustracking.v1.BoundingBox
	(*FloorPoint)(nil),        // 4: continuoustracking.v1.FloorPoint
	(*IdentityRevision)(nil),  // 5: continuoustracking.v1.IdentityRevision
	(*IdentityCandidate)(nil), // 6: continuoustracking.v1.IdentityCandidate
}
var file_continuoustracking_v1_tracking_proto_depIdxs = []int32{
	1, // 0: continuoustracking.v1.TrackingEvent.frame_ref:type_name -> continuoustracking.v1.FrameRef
	2, // 1: continuoustracking.v1.TrackingEvent.detections:type_name -> continuoustracking.v1.Detection
	5, // 2: continuoustracking.v1.TrackingEvent.identity_revisions:type_name -> continuoustracking.v1.IdentityRevision
	3, // 3: continuoustracking.v1.Detection.bbox:type_name -> continuoustracking.v1.BoundingBox
	4, // 4: continuoustracking.v1.Detection.floor_point:type_name -> continuoustracking.v1.FloorPoint
	6, // 5: continuoustracking.v1.IdentityRevision.candidates:type_name -> continuoustracking.v1.IdentityCandidate
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_continuoustracking_v1_tracking_proto_init() }
func file_continuoustracking_v1_tracking_proto_init() {
	if File_continuoustracking_v1_tracking_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_continuoustracking_v1_tracking_proto_rawDesc), len(file_continuoustracking_v1_tracking_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_continuoustracking_v1_tracking_proto_goTypes,
		DependencyIndexes: file_continuoustracking_v1_tracking_proto_depIdxs,
		MessageInfos:      file_continuoustracking_v1_tracking_proto_msgTypes,
	}.Build()
	File_continuoustracking_v1_tracking_proto = out.File
	file_continuoustracking_v1_tracking_proto_goTypes = nil
	file_continuoustracking_v1_tracking_proto_depIdxs = nil
}
