// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: continuoustracking/v1/tracking.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TrackingEvent is the core message produced by the tracking-orchestrator
// after processing a frame. It carries the Bayesian identity posterior,
// spatial coordinates, and temporal metadata.
type TrackingEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identity of the camera stream (matches RTSP ingress config).
	CameraId string `protobuf:"bytes,1,opt,name=camera_id,json=cameraId,proto3" json:"camera_id,omitempty"`
	// Wall-clock time when the event was committed (not when frame arrived).
	// Used as the authoritative timestamp for ordering.
	EventTimeUnixNs uint64 `protobuf:"fixed64,2,opt,name=event_time_unix_ns,json=eventTimeUnixNs,proto3" json:"event_time_unix_ns,omitempty"`
	// Frame-level metadata.
	FrameRef *FrameRef `protobuf:"bytes,3,opt,name=frame_ref,json=frameRef,proto3" json:"frame_ref,omitempty"`
	// One entry per detected person in the frame.
	Detections []*Detection `protobuf:"bytes,4,rep,name=detections,proto3" json:"detections,omitempty"`
	// Identity resolution: for each PH that was matched to a known
	// person, the posterior probability distribution over candidates.
	// DEPRECATED: prefer identity_snapshots (field 8).  This field is kept
	// for one compatibility release and will stop being populated afterward.
	//
	// Deprecated: Marked as deprecated in continuoustracking/v1/tracking.proto.
	IdentityRevisions []*IdentityRevision `protobuf:"bytes,5,rep,name=identity_revisions,json=identityRevisions,proto3" json:"identity_revisions,omitempty"`
	// Resolved room name for the camera at event time. Empty when the camera
	// has no room mapping configured. The CC LocationWriter uses this to
	// open / close PersonLocationHistory rows on room transitions.
	RoomName string `protobuf:"bytes,6,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	// Unique event identifier for tracing / audit. UUID4.
	EventId string `protobuf:"bytes,7,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// Identity snapshots: lightweight per-global-track identity state for
	// live display.  Replaces the dual-purpose identity_revisions field (5)
	// which conflated per-frame snapshots with standalone revision messages.
	IdentitySnapshots []*IdentitySnapshot `protobuf:"bytes,8,rep,name=identity_snapshots,json=identitySnapshots,proto3" json:"identity_snapshots,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TrackingEvent) Reset() {
	*x = TrackingEvent{}
	mi := &file_continuoustracking_v1_tracking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackingEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackingEvent) ProtoMessage() {}

func (x *TrackingEvent) ProtoReflect() protoreflect.Message {
	mi := &file_continuoustracking_v1_tracking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackingEvent.ProtoReflect.Descriptor instead.
func (*TrackingEvent) Descriptor() ([]byte, []int) {
	return file_continuoustracking_v1_tracking_proto_rawDescGZIP(), []int{0}
}

func (x *TrackingEvent) GetCameraId() string {
	if x != nil {
		return x.CameraId
	}
	return ""
}

func (x *TrackingEvent) GetEventTimeUnixNs() uint64 {
	if x != nil {
		return x.EventTimeUnixNs
	}
	return 0
}

func (x *TrackingEvent) GetFrameRef() *FrameRef {
	if x != nil {
		return x.FrameRef
	}
	return nil
}

func (x *TrackingEvent) GetDetections() []*Detection {
	if x != nil {
		return x.Detections
	}
	return nil
}

// Deprecated: Marked as deprecated in continuoustracking/v1/tracking.proto.
func (x *TrackingEvent) GetIdentityRevisions() []*IdentityRevision {
	if x != nil {
		return x.IdentityRevisions
	}
	return nil
}

func (x *TrackingEvent) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *TrackingEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *TrackingEvent) GetIdentitySnapshots() []*IdentitySnapshot {
	if x != nil {
		return x.IdentitySnapshots
	}
	return nil
}

// FrameRef points to a frame stored in MinIO without duplicating pixel data.
type FrameRef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// MinIO object key for the original frame.
	MinioKey string `protobuf:"bytes,1,opt,name=minio_key,json=minioKey,proto3" json:"minio_key,omitempty"`
	// Frame resolution.
	Width  int32 `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height int32 `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	// Frame index within the camera stream (monotonically increasing).
	FrameIndex int64 `protobuf:"varint,4,opt,name=frame_index,json=frameIndex,proto3" json:"frame_index,omitempty"`
	// Capture time from the RTSP source (pre-NTP correction).
	CaptureTimeUnixNs uint64 `protobuf:"fixed64,5,opt,name=capture_time_unix_ns,json=captureTimeUnixNs,proto3" json:"capture_time_unix_ns,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *FrameRef) Reset() {
	*x = FrameRef{}
	mi := &file_continuoustracking_v1_tracking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrameRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameRef) ProtoMessage() {}

func (x *FrameRef) ProtoReflect() protoreflect.Message {
	mi := &file_continuoustracking_v1_tracking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameRef.ProtoReflect.Descriptor instead.
func (*FrameRef) Descriptor() ([]byte, []int) {
	return file_continuoustracking_v1_tracking_proto_rawDescGZIP(), []int{1}
}

func (x *FrameRef) GetMinioKey() string {
	if x != nil {
		return x.MinioKey
	}
	return ""
}

func (x *FrameRef) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *FrameRef) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *FrameRef) GetFrameIndex() int64 {
	if x != nil {
		return x.FrameIndex
	}
	return 0
}

func (x *FrameRef) GetCaptureTimeUnixNs() uint64 {
	if x != nil {
		return x.CaptureTimeUnixNs
	}
	return 0
}

// Detection represents one person detected in a single frame.
type Detection struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique per-frame identifier for this detection bounding box.
	DetectionId string `protobuf:"bytes,1,opt,name=detection_id,json=detectionId,proto3" json:"detection_id,omitempty"`
	// Bounding box in pixel coordinates (top-left origin).
	Bbox *BoundingBox `protobuf:"bytes,2,opt,name=bbox,proto3" json:"bbox,omitempty"`
	// Embedding vector from the ReID model (L2-normalized, float32).
	// The canonical production model is SOLIDER-REID with 768 dimensions.
	Embedding []float32 `protobuf:"fixed32,3,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	// Confidence score from the detection model (0.0 to 1.0).
	Confidence float32 `protobuf:"fixed32,4,opt,name=confidence,proto3" json:"confidence,omitempty"`
	// Floor point in the shared floor-plan coordinate system (millimetres).
	// {x_mm=0, y_mm=0, calibrated=false} when the source camera lacks a
	// homography or the projection is degenerate.
	FloorPoint *FloorPoint `protobuf:"bytes,7,opt,name=floor_point,json=floorPoint,proto3" json:"floor_point,omitempty"`
	// RTMPose 17 COCO keypoints (normalised to [0,1] within the bbox crop).
	// Empty when pose estimation is disabled or the crop is too small.
	PoseKeypoints []*PoseKeypoint `protobuf:"bytes,9,rep,name=pose_keypoints,json=poseKeypoints,proto3" json:"pose_keypoints,omitempty"`
	// Last 12 foot-point positions for this tracklet (camera-frame normalised
	// coords [0,1]). Oldest entry first. Empty until the tracklet has history.
	Trail []*TrailPoint `protobuf:"bytes,10,rep,name=trail,proto3" json:"trail,omitempty"`
	// Posterior evidence snapshot from the identity resolver.
	Evidence *PosteriorEvidence `protobuf:"bytes,11,opt,name=evidence,proto3" json:"evidence,omitempty"`
	// Floor position in the shared floor-plan frame, in metres.
	// Both are 0.0 when the source camera is not calibrated.
	FloorX float32 `protobuf:"fixed32,12,opt,name=floor_x,json=floorX,proto3" json:"floor_x,omitempty"`
	FloorY float32 `protobuf:"fixed32,13,opt,name=floor_y,json=floorY,proto3" json:"floor_y,omitempty"`
	// Classified posture: standing | sitting | walking | lying | unknown.
	Posture string `protobuf:"bytes,14,opt,name=posture,proto3" json:"posture,omitempty"`
	// Person Hypothesis ID assigned by the world-coordinate tracker.
	PhId          string `protobuf:"bytes,15,opt,name=ph_id,json=phId,proto3" json:"ph_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Detection) Reset() {
	*x = Detection{}
	mi := &file_continuoustracking_v1_tracking_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Detection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Detection) ProtoMessage() {}

func (x *Detection) ProtoReflect() protoreflect.Message {
	mi := &file_continuoustracking_v1_tracking_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Detection.ProtoReflect.Descriptor instead.
func (*Detection) Descriptor() ([]byte, []int) {
	return file_continuoustracking_v1_tracking_proto_rawDescGZIP(), []int{2}
}

func (x *Detection) GetDetectionId() string {
	if x != nil {
		return x.DetectionId
	}
	return ""
}

func (x *Detection) GetBbox() *BoundingBox {
	if x != nil {
		return x.Bbox
	}
	return nil
}

func (x *Detection) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

func (x *Detection) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Detection) GetFloorPoint() *FloorPoint {
	if x != nil {
		return x.FloorPoint
	}
	return nil
}

func (x *Detection) GetPoseKeypoints() []*PoseKeypoint {
	if x != nil {
		return x.PoseKeypoints
	}
	return nil
}

func (x *Detection) GetTrail() []*TrailPoint {
	if x != nil {
		return x.Trail
	}
	return nil
}

func (x *Detection) GetEvidence() *PosteriorEvidence {
	if x != nil {
		return x.Evidence
	}
	return nil
}

func (x *Detection) GetFloorX() float32 {
	if x != nil {
		return x.FloorX
	}
	return 0
}

func (x *Detection) GetFloorY() float32 {
	if x != nil {
		return x.FloorY
	}
	return 0
}

func (x *Detection) GetPosture() string {
	if x != nil {
		return x.Posture
	}
	return ""
}

func (x *Detection) GetPhId() string {
	if x != nil {
		return x.PhId
	}
	return ""
}

// PoseKeypoint is one of the 17 COCO body keypoints.
type PoseKeypoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`         // horizontal position normalised to bbox crop [0, 1]
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`         // vertical position normalised to bbox crop [0, 1]
	Score         float32                `protobuf:"fixed32,3,opt,name=score,proto3" json:"score,omitempty"` // visibility confidence [0, 1]
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PoseKeypoint) Reset() {
	*x = PoseKeypoint{}
	mi := &file_continuoustracking_v1_tracking_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoseKeypoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoseKeypoint) ProtoMessage() {}

func (x *PoseKeypoint) ProtoReflect() protoreflect.Message {
	mi := &file_continuoustracking_v1_tracking_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoseKeypoint.ProtoReflect.Descriptor instead.
func (*PoseKeypoint) Descriptor() ([]byte, []int) {
	return file_continuoustracking_v1_tracking_proto_rawDescGZIP(), []int{3}
}

func (x *PoseKeypoint) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PoseKeypoint) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *PoseKeypoint) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

// TrailPoint is a historical foot-point position in camera-frame coords.
type TrailPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"` // normalised horizontal [0, 1]
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"` // normalised vertical [0, 1]
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrailPoint) Reset() {
	*x = TrailPoint{}
	mi := &file_continuoustracking_v1_tracking_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrailPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrailPoint) ProtoMessage() {}

func (x *TrailPoint) ProtoReflect() protoreflect.Message {
	mi := &file_continuoustracking_v1_tracking_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrailPoint.ProtoReflect.Descriptor instead.
func (*TrailPoint) Descriptor() ([]byte, []int) {
	return file_continuoustracking_v1_tracking_proto_rawDescGZIP(), []int{4}
}

func (x *TrailPoint) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *TrailPoint) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

// PosteriorEvidence captures the identity resolver's confidence snapshot.
type PosteriorEvidence struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TopProb        float32                `protobuf:"fixed32,1,opt,name=top_prob,json=topProb,proto3" json:"top_prob,omitempty"`                       // P(top identity | observations)
	Top2Prob       float32                `protobuf:"fixed32,2,opt,name=top2_prob,json=top2Prob,proto3" json:"top2_prob,omitempty"`                    // P(second-best identity | observations)
	FaceAnchorUsed bool                   `protobuf:"varint,3,opt,name=face_anchor_used,json=faceAnchorUsed,proto3" json:"face_anchor_used,omitempty"` // true when a face anchor drove the commit
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PosteriorEvidence) Reset() {
	*x = PosteriorEvidence{}
	mi := &file_continuoustracking_v1_tracking_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PosteriorEvidence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PosteriorEvidence) ProtoMessage() {}

func (x *PosteriorEvidence) ProtoReflect() protoreflect.Message {
	mi := &file_continuoustracking_v1_tracking_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PosteriorEvidence.ProtoReflect.Descriptor instead.
func (*PosteriorEvidence) Descriptor() ([]byte, []int) {
	return file_continuoustracking_v1_tracking_proto_rawDescGZIP(), []int{5}
}

func (x *PosteriorEvidence) GetTopProb() float32 {
	if x != nil {
		return x.TopProb
	}
	return 0
}

func (x *PosteriorEvidence) GetTop2Prob() float32 {
	if x != nil {
		return x.Top2Prob
	}
	return 0
}

func (x *PosteriorEvidence) GetFaceAnchorUsed() bool {
	if x != nil {
		return x.FaceAnchorUsed
	}
	return false
}

// BoundingBox in pixel coordinates: top-left origin, width/height positive.
type BoundingBox struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	XMin          int32                  `protobuf:"varint,1,opt,name=x_min,json=xMin,proto3" json:"x_min,omitempty"`
	YMin          int32                  `protobuf:"varint,2,opt,name=y_min,json=yMin,proto3" json:"y_min,omitempty"`
	XMax          int32                  `protobuf:"varint,3,opt,name=x_max,json=xMax,proto3" json:"x_max,omitempty"`
	YMax          int32                  `protobuf:"varint,4,opt,name=y_max,json=yMax,proto3" json:"y_max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoundingBox) Reset() {
	*x = BoundingBox{}
	mi := &file_continuoustracking_v1_tracking_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoundingBox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoundingBox) ProtoMessage() {}

func (x *BoundingBox) ProtoReflect() protoreflect.Message {
	mi := &file_continuoustracking_v1_tracking_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoundingBox.ProtoReflect.Descriptor instead.
func (*BoundingBox) Descriptor() ([]byte, []int) {
	return file_continuoustracking_v1_tracking_proto_rawDescGZIP(), []int{6}
}

func (x *BoundingBox) GetXMin() int32 {
	if x != nil {
		return x.XMin
	}
	return 0
}

func (x *BoundingBox) GetYMin() int32 {
	if x != nil {
		return x.YMin
	}
	return 0
}

func (x *BoundingBox) GetXMax() int32 {
	if x != nil {
		return x.XMax
	}
	return 0
}

func (x *BoundingBox) GetYMax() int32 {
	if x != nil {
		return x.YMax
	}
	return 0
}

// FloorPoint is a 2D point in the shared floor-plan coordinate system, in
// millimetres.  When calibrated=true the coordinates are consistent across
// all cameras that share the same floor_plan_id.  When calibrated=false
// both coordinates are zero and must not be used for metric comparisons.
type FloorPoint struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// X coordinate in the shared floor-plan frame, in mm.
	XMm int64 `protobuf:"varint,1,opt,name=x_mm,json=xMm,proto3" json:"x_mm,omitempty"`
	// Y coordinate in the shared floor-plan frame, in mm.
	YMm int64 `protobuf:"varint,2,opt,name=y_mm,json=yMm,proto3" json:"y_mm,omitempty"`
	// Whether the homography was calibrated for the source camera.
	Calibrated    bool `protobuf:"varint,3,opt,name=calibrated,proto3" json:"calibrated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FloorPoint) Reset() {
	*x = FloorPoint{}
	mi := &file_continuoustracking_v1_tracking_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FloorPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FloorPoint) ProtoMessage() {}

func (x *FloorPoint) ProtoReflect() protoreflect.Message {
	mi := &file_continuoustracking_v1_tracking_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FloorPoint.ProtoReflect.Descriptor instead.
func (*FloorPoint) Descriptor() ([]byte, []int) {
	return file_continuoustracking_v1_tracking_proto_rawDescGZIP(), []int{7}
}

func (x *FloorPoint) GetXMm() int64 {
	if x != nil {
		return x.XMm
	}
	return 0
}

func (x *FloorPoint) GetYMm() int64 {
	if x != nil {
		return x.YMm
	}
	return 0
}

func (x *FloorPoint) GetCalibrated() bool {
	if x != nil {
		return x.Calibrated
	}
	return false
}

// IdentityRevision is published to the tracking.revisions Redis Stream
// when an identity assignment for a Person Hypothesis changes.
// N0: renamed global_track_id -> ph_id; tracklet_ids reserved.
type IdentityRevision struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Person Hypothesis whose identity is being revised.
	PhId string `protobuf:"bytes,1,opt,name=ph_id,json=phId,proto3" json:"ph_id,omitempty"`
	// Probability distribution over candidate identities.
	// N0: unused by the PH-native revision; kept for wire compatibility.
	Candidates []*IdentityCandidate `protobuf:"bytes,2,rep,name=candidates,proto3" json:"candidates,omitempty"`
	// The MAP (maximum a posteriori) estimate.
	// N0: unused; kept for wire compatibility.
	MapIdentityId string `protobuf:"bytes,3,opt,name=map_identity_id,json=mapIdentityId,proto3" json:"map_identity_id,omitempty"`
	// Entropy of the posterior (measure of uncertainty, in bits).
	// Lower = more certain.
	// N0: unused at this field; posterior_entropy moved into evidence_json.
	PosteriorEntropy float32 `protobuf:"fixed32,4,opt,name=posterior_entropy,json=posteriorEntropy,proto3" json:"posterior_entropy,omitempty"`
	// When this revision was computed.
	RevisionTimeUnixNs uint64 `protobuf:"fixed64,5,opt,name=revision_time_unix_ns,json=revisionTimeUnixNs,proto3" json:"revision_time_unix_ns,omitempty"`
	// Unique ID of this revision. Used for idempotent CC-side rewrites.
	RevisionId string `protobuf:"bytes,6,opt,name=revision_id,json=revisionId,proto3" json:"revision_id,omitempty"`
	// Identity before the revision (empty when promoting from UNKNOWN).
	PreviousIdentityId string `protobuf:"bytes,8,opt,name=previous_identity_id,json=previousIdentityId,proto3" json:"previous_identity_id,omitempty"`
	// Identity after the revision (empty when demoting to UNKNOWN).
	NewIdentityId string `protobuf:"bytes,9,opt,name=new_identity_id,json=newIdentityId,proto3" json:"new_identity_id,omitempty"`
	// Human-readable reason: initial_assignment | identity_change |
	// demoted_to_unknown | manual_override | merge.
	Reason string `protobuf:"bytes,10,opt,name=reason,proto3" json:"reason,omitempty"`
	// N0: evidence_json extended with actor, rewritten_rows, observation_count,
	// and evidence_sources in addition to the legacy posterior fields.
	EvidenceJson  string `protobuf:"bytes,11,opt,name=evidence_json,json=evidenceJson,proto3" json:"evidence_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentityRevision) Reset() {
	*x = IdentityRevision{}
	mi := &file_continuoustracking_v1_tracking_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityRevision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityRevision) ProtoMessage() {}

func (x *IdentityRevision) ProtoReflect() protoreflect.Message {
	mi := &file_continuoustracking_v1_tracking_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityRevision.ProtoReflect.Descriptor instead.
func (*IdentityRevision) Descriptor() ([]byte, []int) {
	return file_continuoustracking_v1_tracking_proto_rawDescGZIP(), []int{8}
}

func (x *IdentityRevision) GetPhId() string {
	if x != nil {
		return x.PhId
	}
	return ""
}

func (x *IdentityRevision) GetCandidates() []*IdentityCandidate {
	if x != nil {
		return x.Candidates
	}
	return nil
}

func (x *IdentityRevision) GetMapIdentityId() string {
	if x != nil {
		return x.MapIdentityId
	}
	return ""
}

func (x *IdentityRevision) GetPosteriorEntropy() float32 {
	if x != nil {
		return x.PosteriorEntropy
	}
	return 0
}

func (x *IdentityRevision) GetRevisionTimeUnixNs() uint64 {
	if x != nil {
		return x.RevisionTimeUnixNs
	}
	return 0
}

func (x *IdentityRevision) GetRevisionId() string {
	if x != nil {
		return x.RevisionId
	}
	return ""
}

func (x *IdentityRevision) GetPreviousIdentityId() string {
	if x != nil {
		return x.PreviousIdentityId
	}
	return ""
}

func (x *IdentityRevision) GetNewIdentityId() string {
	if x != nil {
		return x.NewIdentityId
	}
	return ""
}

func (x *IdentityRevision) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *IdentityRevision) GetEvidenceJson() string {
	if x != nil {
		return x.EvidenceJson
	}
	return ""
}

// IdentitySnapshot is a lightweight per-PH identity state for live
// display.  Unlike IdentityRevision, it is not a standalone stream message —
// it only appears as a sub-message of TrackingEvent.
type IdentitySnapshot struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// R3: canonical field name.  Field number 1 is unchanged; binary wire is
	// compatible.  The old name "global_track_id" is reserved to prevent
	// accidental JSON/text-format reuse.
	PhId string `protobuf:"bytes,1,opt,name=ph_id,json=phId,proto3" json:"ph_id,omitempty"`
	// The committed identity for this global track (empty when UNKNOWN).
	IdentityId string `protobuf:"bytes,2,opt,name=identity_id,json=identityId,proto3" json:"identity_id,omitempty"`
	// Probability of the top identity from the posterior.
	TopProbability float32 `protobuf:"fixed32,3,opt,name=top_probability,json=topProbability,proto3" json:"top_probability,omitempty"`
	// Probability of the second-best identity from the posterior.
	SecondProbability float32 `protobuf:"fixed32,4,opt,name=second_probability,json=secondProbability,proto3" json:"second_probability,omitempty"`
	// Entropy of the full posterior (bits). Lower = more certain.
	PosteriorEntropy float32 `protobuf:"fixed32,5,opt,name=posterior_entropy,json=posteriorEntropy,proto3" json:"posterior_entropy,omitempty"`
	// Whether direct face evidence (ArcFace) contributed to this decision.
	DirectFaceEvidence bool `protobuf:"varint,6,opt,name=direct_face_evidence,json=directFaceEvidence,proto3" json:"direct_face_evidence,omitempty"`
	// Evidence source summary serialised as JSON:
	// {"sources": {"direct_face": 1, "reid": 3}, "direct_face_confidence": 0.95, ...}
	EvidenceJson string `protobuf:"bytes,7,opt,name=evidence_json,json=evidenceJson,proto3" json:"evidence_json,omitempty"`
	// Exponential moving average of crop-quality scores for this PH (U1/U2).
	// Range [0, 1]; 0.0 means no quality data yet.  Consumed by CC to populate
	// PersonLocationEnvelope.quality without client-side inference (design rule D5).
	MeanQuality   float32 `protobuf:"fixed32,8,opt,name=mean_quality,json=meanQuality,proto3" json:"mean_quality,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentitySnapshot) Reset() {
	*x = IdentitySnapshot{}
	mi := &file_continuoustracking_v1_tracking_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentitySnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentitySnapshot) ProtoMessage() {}

func (x *IdentitySnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_continuoustracking_v1_tracking_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentitySnapshot.ProtoReflect.Descriptor instead.
func (*IdentitySnapshot) Descriptor() ([]byte, []int) {
	return file_continuoustracking_v1_tracking_proto_rawDescGZIP(), []int{9}
}

func (x *IdentitySnapshot) GetPhId() string {
	if x != nil {
		return x.PhId
	}
	return ""
}

func (x *IdentitySnapshot) GetIdentityId() string {
	if x != nil {
		return x.IdentityId
	}
	return ""
}

func (x *IdentitySnapshot) GetTopProbability() float32 {
	if x != nil {
		return x.TopProbability
	}
	return 0
}

func (x *IdentitySnapshot) GetSecondProbability() float32 {
	if x != nil {
		return x.SecondProbability
	}
	return 0
}

func (x *IdentitySnapshot) GetPosteriorEntropy() float32 {
	if x != nil {
		return x.PosteriorEntropy
	}
	return 0
}

func (x *IdentitySnapshot) GetDirectFaceEvidence() bool {
	if x != nil {
		return x.DirectFaceEvidence
	}
	return false
}

func (x *IdentitySnapshot) GetEvidenceJson() string {
	if x != nil {
		return x.EvidenceJson
	}
	return ""
}

func (x *IdentitySnapshot) GetMeanQuality() float32 {
	if x != nil {
		return x.MeanQuality
	}
	return 0
}

// IdentityCandidate is one candidate identity with its posterior probability.
type IdentityCandidate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The identity's gallery entry ID.
	IdentityId string `protobuf:"bytes,1,opt,name=identity_id,json=identityId,proto3" json:"identity_id,omitempty"`
	// Display name for the identity.
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Posterior probability P(identity | observations).
	Probability   float32 `protobuf:"fixed32,3,opt,name=probability,proto3" json:"probability,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentityCandidate) Reset() {
	*x = IdentityCandidate{}
	mi := &file_continuoustracking_v1_tracking_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityCandidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityCandidate) ProtoMessage() {}

func (x *IdentityCandidate) ProtoReflect() protoreflect.Message {
	mi := &file_continuoustracking_v1_tracking_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityCandidate.ProtoReflect.Descriptor instead.
func (*IdentityCandidate) Descriptor() ([]byte, []int) {
	return file_continuoustracking_v1_tracking_proto_rawDescGZIP(), []int{10}
}

func (x *IdentityCandidate) GetIdentityId() string {
	if x != nil {
		return x.IdentityId
	}
	return ""
}

func (x *IdentityCandidate) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *IdentityCandidate) GetProbability() float32 {
	if x != nil {
		return x.Probability
	}
	return 0
}

var File_continuoustracking_v1_tracking_proto protoreflect.FileDescriptor

const file_continuoustracking_v1_tracking_proto_rawDesc = "" +
	"\n" +
	"$continuoustracking/v1/tracking.proto\x12\x15continuoustracking.v1\"\xc5\x03\n" +
	"\rTrackingEvent\x12\x1b\n" +
	"\tcamera_id\x18\x01 \x01(\tR\bcameraId\x12+\n" +
	"\x12event_time_unix_ns\x18\x02 \x01(\x06R\x0feventTimeUnixNs\x12<\n" +
	"\tframe_ref\x18\x03 \x01(\v2\x1f.continuoustracking.v1.FrameRefR\bframeRef\x12@\n" +
	"\n" +
	"detections\x18\x04 \x03(\v2 .continuoustracking.v1.DetectionR\n" +
	"detections\x12Z\n" +
	"\x12identity_revisions\x18\x05 \x03(\v2'.continuoustracking.v1.IdentityRevisionB\x02\x18\x01R\x11identityRevisions\x12\x1b\n" +
	"\troom_name\x18\x06 \x01(\tR\broomName\x12\x19\n" +
	"\bevent_id\x18\a \x01(\tR\aeventId\x12V\n" +
	"\x12identity_snapshots\x18\b \x03(\v2'.continuoustracking.v1.IdentitySnapshotR\x11identitySnapshots\"\xa7\x01\n" +
	"\bFrameRef\x12\x1b\n" +
	"\tminio_key\x18\x01 \x01(\tR\bminioKey\x12\x14\n" +
	"\x05width\x18\x02 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x05R\x06height\x12\x1f\n" +
	"\vframe_index\x18\x04 \x01(\x03R\n" +
	"frameIndex\x12/\n" +
	"\x14capture_time_unix_ns\x18\x05 \x01(\x06R\x11captureTimeUnixNs\"\xbe\x04\n" +
	"\tDetection\x12!\n" +
	"\fdetection_id\x18\x01 \x01(\tR\vdetectionId\x126\n" +
	"\x04bbox\x18\x02 \x01(\v2\".continuoustracking.v1.BoundingBoxR\x04bbox\x12\x1c\n" +
	"\tembedding\x18\x03 \x03(\x02R\tembedding\x12\x1e\n" +
	"\n" +
	"confidence\x18\x04 \x01(\x02R\n" +
	"confidence\x12B\n" +
	"\vfloor_point\x18\a \x01(\v2!.continuoustracking.v1.FloorPointR\n" +
	"floorPoint\x12J\n" +
	"\x0epose_keypoints\x18\t \x03(\v2#.continuoustracking.v1.PoseKeypointR\rposeKeypoints\x127\n" +
	"\x05trail\x18\n" +
	" \x03(\v2!.continuoustracking.v1.TrailPointR\x05trail\x12D\n" +
	"\bevidence\x18\v \x01(\v2(.continuoustracking.v1.PosteriorEvidenceR\bevidence\x12\x17\n" +
	"\afloor_x\x18\f \x01(\x02R\x06floorX\x12\x17\n" +
	"\afloor_y\x18\r \x01(\x02R\x06floorY\x12\x18\n" +
	"\aposture\x18\x0e \x01(\tR\aposture\x12\x13\n" +
	"\x05ph_id\x18\x0f \x01(\tR\x04phIdJ\x04\b\x05\x10\x06J\x04\b\x06\x10\aR\vtracklet_idR\x0fglobal_track_id\"@\n" +
	"\fPoseKeypoint\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x02R\x05score\"(\n" +
	"\n" +
	"TrailPoint\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\"u\n" +
	"\x11PosteriorEvidence\x12\x19\n" +
	"\btop_prob\x18\x01 \x01(\x02R\atopProb\x12\x1b\n" +
	"\ttop2_prob\x18\x02 \x01(\x02R\btop2Prob\x12(\n" +
	"\x10face_anchor_used\x18\x03 \x01(\bR\x0efaceAnchorUsed\"a\n" +
	"\vBoundingBox\x12\x13\n" +
	"\x05x_min\x18\x01 \x01(\x05R\x04xMin\x12\x13\n" +
	"\x05y_min\x18\x02 \x01(\x05R\x04yMin\x12\x13\n" +
	"\x05x_max\x18\x03 \x01(\x05R\x04xMax\x12\x13\n" +
	"\x05y_max\x18\x04 \x01(\x05R\x04yMax\"R\n" +
	"\n" +
	"FloorPoint\x12\x11\n" +
	"\x04x_mm\x18\x01 \x01(\x03R\x03xMm\x12\x11\n" +
	"\x04y_mm\x18\x02 \x01(\x03R\x03yMm\x12\x1e\n" +
	"\n" +
	"calibrated\x18\x03 \x01(\bR\n" +
	"calibrated\"\xb7\x03\n" +
	"\x10IdentityRevision\x12\x13\n" +
	"\x05ph_id\x18\x01 \x01(\tR\x04phId\x12H\n" +
	"\n" +
	"candidates\x18\x02 \x03(\v2(.continuoustracking.v1.IdentityCandidateR\n" +
	"candidates\x12&\n" +
	"\x0fmap_identity_id\x18\x03 \x01(\tR\rmapIdentityId\x12+\n" +
	"\x11posterior_entropy\x18\x04 \x01(\x02R\x10posteriorEntropy\x121\n" +
	"\x15revision_time_unix_ns\x18\x05 \x01(\x06R\x12revisionTimeUnixNs\x12\x1f\n" +
	"\vrevision_id\x18\x06 \x01(\tR\n" +
	"revisionId\x120\n" +
	"\x14previous_identity_id\x18\b \x01(\tR\x12previousIdentityId\x12&\n" +
	"\x0fnew_identity_id\x18\t \x01(\tR\rnewIdentityId\x12\x16\n" +
	"\x06reason\x18\n" +
	" \x01(\tR\x06reason\x12#\n" +
	"\revidence_json\x18\v \x01(\tR\fevidenceJsonJ\x04\b\a\x10\b\"\xd8\x02\n" +
	"\x10IdentitySnapshot\x12\x13\n" +
	"\x05ph_id\x18\x01 \x01(\tR\x04phId\x12\x1f\n" +
	"\videntity_id\x18\x02 \x01(\tR\n" +
	"identityId\x12'\n" +
	"\x0ftop_probability\x18\x03 \x01(\x02R\x0etopProbability\x12-\n" +
	"\x12second_probability\x18\x04 \x01(\x02R\x11secondProbability\x12+\n" +
	"\x11posterior_entropy\x18\x05 \x01(\x02R\x10posteriorEntropy\x120\n" +
	"\x14direct_face_evidence\x18\x06 \x01(\bR\x12directFaceEvidence\x12#\n" +
	"\revidence_json\x18\a \x01(\tR\fevidenceJson\x12!\n" +
	"\fmean_quality\x18\b \x01(\x02R\vmeanQualityR\x0fglobal_track_id\"y\n" +
	"\x11IdentityCandidate\x12\x1f\n" +
	"\videntity_id\x18\x01 \x01(\tR\n" +
	"identityId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12 \n" +
	"\vprobability\x18\x03 \x01(\x02R\vprobabilityBOZMgithub.com/SilverMind-Project/continuous-tracking/proto/continuoustracking/v1b\x06proto3"

var (
	file_continuoustracking_v1_tracking_proto_rawDescOnce sync.Once
	file_continuoustracking_v1_tracking_proto_rawDescData []byte
)

func file_continuoustracking_v1_tracking_proto_rawDescGZIP() []byte {
	file_continuoustracking_v1_tracking_proto_rawDescOnce.Do(func() {
		file_continuoustracking_v1_tracking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_continuoustracking_v1_tracking_proto_rawDesc), len(file_continuoustracking_v1_tracking_proto_rawDesc)))
	})
	return file_continuoustracking_v1_tracking_proto_rawDescData
}

var file_continuoustracking_v1_tracking_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_continuoustracking_v1_tracking_proto_goTypes = []any{
	(*TrackingEvent)(nil),     // 0: continuoustracking.v1.TrackingEvent
	(*FrameRef)(nil),          // 1: continuoustracking.v1.FrameRef
	(*Detection)(nil),         // 2: continuoustracking.v1.Detection
	(*PoseKeypoint)(nil),      // 3: continuoustracking.v1.PoseKeypoint
	(*TrailPoint)(nil),        // 4: continuoustracking.v1.TrailPoint
	(*PosteriorEvidence)(nil), // 5: continuoustracking.v1.PosteriorEvidence
	(*BoundingBox)(nil),       // 6: continuoustracking.v1.BoundingBox
	(*FloorPoint)(nil),        // 7: continuoustracking.v1.FloorPoint
	(*IdentityRevision)(nil),  // 8: continuoustracking.v1.IdentityRevision
	(*IdentitySnapshot)(nil),  // 9: continuoustracking.v1.IdentitySnapshot
	(*IdentityCandidate)(nil), // 10: continuoustracking.v1.IdentityCandidate
}
var file_continuoustracking_v1_tracking_proto_depIdxs = []int32{
	1,  // 0: continuoustracking.v1.TrackingEvent.frame_ref:type_name -> continuoustracking.v1.FrameRef
	2,  // 1: continuoustracking.v1.TrackingEvent.detections:type_name -> continuoustracking.v1.Detection
	8,  // 2: continuoustracking.v1.TrackingEvent.identity_revisions:type_name -> continuoustracking.v1.IdentityRevision
	9,  // 3: continuoustracking.v1.TrackingEvent.identity_snapshots:type_name -> continuoustracking.v1.IdentitySnapshot
	6,  // 4: continuoustracking.v1.Detection.bbox:type_name -> continuoustracking.v1.BoundingBox
	7,  // 5: continuoustracking.v1.Detection.floor_point:type_name -> continuoustracking.v1.FloorPoint
	3,  // 6: continuoustracking.v1.Detection.pose_keypoints:type_name -> continuoustracking.v1.PoseKeypoint
	4,  // 7: continuoustracking.v1.Detection.trail:type_name -> continuoustracking.v1.TrailPoint
	5,  // 8: continuoustracking.v1.Detection.evidence:type_name -> continuoustracking.v1.PosteriorEvidence
	10, // 9: continuoustracking.v1.IdentityRevision.candidates:type_name -> continuoustracking.v1.IdentityCandidate
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_continuoustracking_v1_tracking_proto_init() }
func file_continuoustracking_v1_tracking_proto_init() {
	if File_continuoustracking_v1_tracking_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_continuoustracking_v1_tracking_proto_rawDesc), len(file_continuoustracking_v1_tracking_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_continuoustracking_v1_tracking_proto_goTypes,
		DependencyIndexes: file_continuoustracking_v1_tracking_proto_depIdxs,
		MessageInfos:      file_continuoustracking_v1_tracking_proto_msgTypes,
	}.Build()
	File_continuoustracking_v1_tracking_proto = out.File
	file_continuoustracking_v1_tracking_proto_goTypes = nil
	file_continuoustracking_v1_tracking_proto_depIdxs = nil
}
