// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: continuoustracking/v1/tracking.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PresenceEventType int32

const (
	PresenceEventType_PRESENCE_EVENT_TYPE_UNSPECIFIED PresenceEventType = 0
	PresenceEventType_PRESENCE_EVENT_TYPE_APPEARED    PresenceEventType = 1
	PresenceEventType_PRESENCE_EVENT_TYPE_DISAPPEARED PresenceEventType = 2
)

// Enum value maps for PresenceEventType.
var (
	PresenceEventType_name = map[int32]string{
		0: "PRESENCE_EVENT_TYPE_UNSPECIFIED",
		1: "PRESENCE_EVENT_TYPE_APPEARED",
		2: "PRESENCE_EVENT_TYPE_DISAPPEARED",
	}
	PresenceEventType_value = map[string]int32{
		"PRESENCE_EVENT_TYPE_UNSPECIFIED": 0,
		"PRESENCE_EVENT_TYPE_APPEARED":    1,
		"PRESENCE_EVENT_TYPE_DISAPPEARED": 2,
	}
)

func (x PresenceEventType) Enum() *PresenceEventType {
	p := new(PresenceEventType)
	*p = x
	return p
}

func (x PresenceEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PresenceEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_continuoustracking_v1_tracking_proto_enumTypes[0].Descriptor()
}

func (PresenceEventType) Type() protoreflect.EnumType {
	return &file_continuoustracking_v1_tracking_proto_enumTypes[0]
}

func (x PresenceEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PresenceEventType.Descriptor instead.
func (PresenceEventType) EnumDescriptor() ([]byte, []int) {
	return file_continuoustracking_v1_tracking_proto_rawDescGZIP(), []int{0}
}

type DwellEventType int32

const (
	DwellEventType_DWELL_EVENT_TYPE_UNSPECIFIED DwellEventType = 0
	DwellEventType_DWELL_EVENT_TYPE_STARTED     DwellEventType = 1
	DwellEventType_DWELL_EVENT_TYPE_ENDED       DwellEventType = 2
)

// Enum value maps for DwellEventType.
var (
	DwellEventType_name = map[int32]string{
		0: "DWELL_EVENT_TYPE_UNSPECIFIED",
		1: "DWELL_EVENT_TYPE_STARTED",
		2: "DWELL_EVENT_TYPE_ENDED",
	}
	DwellEventType_value = map[string]int32{
		"DWELL_EVENT_TYPE_UNSPECIFIED": 0,
		"DWELL_EVENT_TYPE_STARTED":     1,
		"DWELL_EVENT_TYPE_ENDED":       2,
	}
)

func (x DwellEventType) Enum() *DwellEventType {
	p := new(DwellEventType)
	*p = x
	return p
}

func (x DwellEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DwellEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_continuoustracking_v1_tracking_proto_enumTypes[1].Descriptor()
}

func (DwellEventType) Type() protoreflect.EnumType {
	return &file_continuoustracking_v1_tracking_proto_enumTypes[1]
}

func (x DwellEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DwellEventType.Descriptor instead.
func (DwellEventType) EnumDescriptor() ([]byte, []int) {
	return file_continuoustracking_v1_tracking_proto_rawDescGZIP(), []int{1}
}

// Indicates whether a SceneSample frames an isolated person,
// a crowd, an interaction, or an empty scene.
type SceneSampleKind int32

const (
	SceneSampleKind_SCENE_SAMPLE_KIND_UNSPECIFIED     SceneSampleKind = 0
	SceneSampleKind_SCENE_SAMPLE_KIND_ISOLATED_PERSON SceneSampleKind = 1
	SceneSampleKind_SCENE_SAMPLE_KIND_INTERACTION     SceneSampleKind = 2
	SceneSampleKind_SCENE_SAMPLE_KIND_CROWD           SceneSampleKind = 3
	SceneSampleKind_SCENE_SAMPLE_KIND_EMPTY           SceneSampleKind = 4
)

// Enum value maps for SceneSampleKind.
var (
	SceneSampleKind_name = map[int32]string{
		0: "SCENE_SAMPLE_KIND_UNSPECIFIED",
		1: "SCENE_SAMPLE_KIND_ISOLATED_PERSON",
		2: "SCENE_SAMPLE_KIND_INTERACTION",
		3: "SCENE_SAMPLE_KIND_CROWD",
		4: "SCENE_SAMPLE_KIND_EMPTY",
	}
	SceneSampleKind_value = map[string]int32{
		"SCENE_SAMPLE_KIND_UNSPECIFIED":     0,
		"SCENE_SAMPLE_KIND_ISOLATED_PERSON": 1,
		"SCENE_SAMPLE_KIND_INTERACTION":     2,
		"SCENE_SAMPLE_KIND_CROWD":           3,
		"SCENE_SAMPLE_KIND_EMPTY":           4,
	}
)

func (x SceneSampleKind) Enum() *SceneSampleKind {
	p := new(SceneSampleKind)
	*p = x
	return p
}

func (x SceneSampleKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SceneSampleKind) Descriptor() protoreflect.EnumDescriptor {
	return file_continuoustracking_v1_tracking_proto_enumTypes[2].Descriptor()
}

func (SceneSampleKind) Type() protoreflect.EnumType {
	return &file_continuoustracking_v1_tracking_proto_enumTypes[2]
}

func (x SceneSampleKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SceneSampleKind.Descriptor instead.
func (SceneSampleKind) EnumDescriptor() ([]byte, []int) {
	return file_continuoustracking_v1_tracking_proto_rawDescGZIP(), []int{2}
}

// TrackingEvent is the core message produced by the tracking-orchestrator
// after processing a frame. It carries the Bayesian identity posterior,
// spatial coordinates, and temporal metadata.
type TrackingEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identity of the camera stream (matches RTSP ingress config).
	CameraId string `protobuf:"bytes,1,opt,name=camera_id,json=cameraId,proto3" json:"camera_id,omitempty"`
	// Wall-clock time when the event was committed (not when frame arrived).
	// Used as the authoritative timestamp for ordering.
	EventTimeUnixNs uint64 `protobuf:"fixed64,2,opt,name=event_time_unix_ns,json=eventTimeUnixNs,proto3" json:"event_time_unix_ns,omitempty"`
	// Frame-level metadata.
	FrameRef *FrameRef `protobuf:"bytes,3,opt,name=frame_ref,json=frameRef,proto3" json:"frame_ref,omitempty"`
	// One entry per detected person in the frame.
	Detections []*Detection `protobuf:"bytes,4,rep,name=detections,proto3" json:"detections,omitempty"`
	// Identity resolution: for each PH that was matched to a known
	// person, the posterior probability distribution over candidates.
	// DEPRECATED: prefer identity_snapshots (field 8).  This field is kept
	// for one compatibility release and will stop being populated afterward.
	//
	// Deprecated: Marked as deprecated in continuoustracking/v1/tracking.proto.
	IdentityRevisions []*IdentityRevision `protobuf:"bytes,5,rep,name=identity_revisions,json=identityRevisions,proto3" json:"identity_revisions,omitempty"`
	// Resolved room name for the camera at event time. Empty when the camera
	// has no room mapping configured. The CC LocationWriter uses this to
	// open / close PersonLocationHistory rows on room transitions.
	RoomName string `protobuf:"bytes,6,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	// Unique event identifier for tracing / audit. UUID4.
	EventId string `protobuf:"bytes,7,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// Identity snapshots: lightweight per-global-track identity state for
	// live display.  Replaces the dual-purpose identity_revisions field (5)
	// which conflated per-frame snapshots with standalone revision messages.
	IdentitySnapshots []*IdentitySnapshot `protobuf:"bytes,8,rep,name=identity_snapshots,json=identitySnapshots,proto3" json:"identity_snapshots,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TrackingEvent) Reset() {
	*x = TrackingEvent{}
	mi := &file_continuoustracking_v1_tracking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackingEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackingEvent) ProtoMessage() {}

func (x *TrackingEvent) ProtoReflect() protoreflect.Message {
	mi := &file_continuoustracking_v1_tracking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackingEvent.ProtoReflect.Descriptor instead.
func (*TrackingEvent) Descriptor() ([]byte, []int) {
	return file_continuoustracking_v1_tracking_proto_rawDescGZIP(), []int{0}
}

func (x *TrackingEvent) GetCameraId() string {
	if x != nil {
		return x.CameraId
	}
	return ""
}

func (x *TrackingEvent) GetEventTimeUnixNs() uint64 {
	if x != nil {
		return x.EventTimeUnixNs
	}
	return 0
}

func (x *TrackingEvent) GetFrameRef() *FrameRef {
	if x != nil {
		return x.FrameRef
	}
	return nil
}

func (x *TrackingEvent) GetDetections() []*Detection {
	if x != nil {
		return x.Detections
	}
	return nil
}

// Deprecated: Marked as deprecated in continuoustracking/v1/tracking.proto.
func (x *TrackingEvent) GetIdentityRevisions() []*IdentityRevision {
	if x != nil {
		return x.IdentityRevisions
	}
	return nil
}

func (x *TrackingEvent) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *TrackingEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *TrackingEvent) GetIdentitySnapshots() []*IdentitySnapshot {
	if x != nil {
		return x.IdentitySnapshots
	}
	return nil
}

// FrameRef points to a frame stored in MinIO without duplicating pixel data.
type FrameRef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// MinIO object key for the original frame.
	MinioKey string `protobuf:"bytes,1,opt,name=minio_key,json=minioKey,proto3" json:"minio_key,omitempty"`
	// Frame resolution.
	Width  int32 `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height int32 `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	// Frame index within the camera stream (monotonically increasing).
	FrameIndex int64 `protobuf:"varint,4,opt,name=frame_index,json=frameIndex,proto3" json:"frame_index,omitempty"`
	// Capture time from the RTSP source (pre-NTP correction).
	CaptureTimeUnixNs uint64 `protobuf:"fixed64,5,opt,name=capture_time_unix_ns,json=captureTimeUnixNs,proto3" json:"capture_time_unix_ns,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *FrameRef) Reset() {
	*x = FrameRef{}
	mi := &file_continuoustracking_v1_tracking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrameRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameRef) ProtoMessage() {}

func (x *FrameRef) ProtoReflect() protoreflect.Message {
	mi := &file_continuoustracking_v1_tracking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameRef.ProtoReflect.Descriptor instead.
func (*FrameRef) Descriptor() ([]byte, []int) {
	return file_continuoustracking_v1_tracking_proto_rawDescGZIP(), []int{1}
}

func (x *FrameRef) GetMinioKey() string {
	if x != nil {
		return x.MinioKey
	}
	return ""
}

func (x *FrameRef) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *FrameRef) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *FrameRef) GetFrameIndex() int64 {
	if x != nil {
		return x.FrameIndex
	}
	return 0
}

func (x *FrameRef) GetCaptureTimeUnixNs() uint64 {
	if x != nil {
		return x.CaptureTimeUnixNs
	}
	return 0
}

// Detection represents one person detected in a single frame.
type Detection struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique per-frame identifier for this detection bounding box.
	DetectionId string `protobuf:"bytes,1,opt,name=detection_id,json=detectionId,proto3" json:"detection_id,omitempty"`
	// Bounding box in pixel coordinates (top-left origin).
	Bbox *BoundingBox `protobuf:"bytes,2,opt,name=bbox,proto3" json:"bbox,omitempty"`
	// Embedding vector from the ReID model (L2-normalized, float32).
	// The canonical production model is SOLIDER-REID with 768 dimensions.
	Embedding []float32 `protobuf:"fixed32,3,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	// Confidence score from the detection model (0.0 to 1.0).
	Confidence float32 `protobuf:"fixed32,4,opt,name=confidence,proto3" json:"confidence,omitempty"`
	// Floor point in the shared floor-plan coordinate system (millimetres).
	// {x_mm=0, y_mm=0, calibrated=false} when the source camera lacks a
	// homography or the projection is degenerate.
	FloorPoint *FloorPoint `protobuf:"bytes,7,opt,name=floor_point,json=floorPoint,proto3" json:"floor_point,omitempty"`
	// RTMPose 17 COCO keypoints (normalised to [0,1] within the bbox crop).
	// Empty when pose estimation is disabled or the crop is too small.
	PoseKeypoints []*PoseKeypoint `protobuf:"bytes,9,rep,name=pose_keypoints,json=poseKeypoints,proto3" json:"pose_keypoints,omitempty"`
	// Last 12 foot-point positions for this tracklet (camera-frame normalised
	// coords [0,1]). Oldest entry first. Empty until the tracklet has history.
	Trail []*TrailPoint `protobuf:"bytes,10,rep,name=trail,proto3" json:"trail,omitempty"`
	// Posterior evidence snapshot from the identity resolver.
	Evidence *PosteriorEvidence `protobuf:"bytes,11,opt,name=evidence,proto3" json:"evidence,omitempty"`
	// Floor position in the shared floor-plan frame, in metres.
	// Both are 0.0 when the source camera is not calibrated.
	FloorX float32 `protobuf:"fixed32,12,opt,name=floor_x,json=floorX,proto3" json:"floor_x,omitempty"`
	FloorY float32 `protobuf:"fixed32,13,opt,name=floor_y,json=floorY,proto3" json:"floor_y,omitempty"`
	// Classified posture: standing | sitting | walking | lying | unknown.
	Posture string `protobuf:"bytes,14,opt,name=posture,proto3" json:"posture,omitempty"`
	// Person Hypothesis ID assigned by the world-coordinate tracker.
	PhId          string `protobuf:"bytes,15,opt,name=ph_id,json=phId,proto3" json:"ph_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Detection) Reset() {
	*x = Detection{}
	mi := &file_continuoustracking_v1_tracking_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Detection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Detection) ProtoMessage() {}

func (x *Detection) ProtoReflect() protoreflect.Message {
	mi := &file_continuoustracking_v1_tracking_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Detection.ProtoReflect.Descriptor instead.
func (*Detection) Descriptor() ([]byte, []int) {
	return file_continuoustracking_v1_tracking_proto_rawDescGZIP(), []int{2}
}

func (x *Detection) GetDetectionId() string {
	if x != nil {
		return x.DetectionId
	}
	return ""
}

func (x *Detection) GetBbox() *BoundingBox {
	if x != nil {
		return x.Bbox
	}
	return nil
}

func (x *Detection) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

func (x *Detection) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Detection) GetFloorPoint() *FloorPoint {
	if x != nil {
		return x.FloorPoint
	}
	return nil
}

func (x *Detection) GetPoseKeypoints() []*PoseKeypoint {
	if x != nil {
		return x.PoseKeypoints
	}
	return nil
}

func (x *Detection) GetTrail() []*TrailPoint {
	if x != nil {
		return x.Trail
	}
	return nil
}

func (x *Detection) GetEvidence() *PosteriorEvidence {
	if x != nil {
		return x.Evidence
	}
	return nil
}

func (x *Detection) GetFloorX() float32 {
	if x != nil {
		return x.FloorX
	}
	return 0
}

func (x *Detection) GetFloorY() float32 {
	if x != nil {
		return x.FloorY
	}
	return 0
}

func (x *Detection) GetPosture() string {
	if x != nil {
		return x.Posture
	}
	return ""
}

func (x *Detection) GetPhId() string {
	if x != nil {
		return x.PhId
	}
	return ""
}

// PoseKeypoint is one of the 17 COCO body keypoints.
type PoseKeypoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`         // horizontal position normalised to bbox crop [0, 1]
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`         // vertical position normalised to bbox crop [0, 1]
	Score         float32                `protobuf:"fixed32,3,opt,name=score,proto3" json:"score,omitempty"` // visibility confidence [0, 1]
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PoseKeypoint) Reset() {
	*x = PoseKeypoint{}
	mi := &file_continuoustracking_v1_tracking_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoseKeypoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoseKeypoint) ProtoMessage() {}

func (x *PoseKeypoint) ProtoReflect() protoreflect.Message {
	mi := &file_continuoustracking_v1_tracking_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoseKeypoint.ProtoReflect.Descriptor instead.
func (*PoseKeypoint) Descriptor() ([]byte, []int) {
	return file_continuoustracking_v1_tracking_proto_rawDescGZIP(), []int{3}
}

func (x *PoseKeypoint) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PoseKeypoint) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *PoseKeypoint) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

// TrailPoint is a historical foot-point position in camera-frame coords.
type TrailPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"` // normalised horizontal [0, 1]
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"` // normalised vertical [0, 1]
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrailPoint) Reset() {
	*x = TrailPoint{}
	mi := &file_continuoustracking_v1_tracking_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrailPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrailPoint) ProtoMessage() {}

func (x *TrailPoint) ProtoReflect() protoreflect.Message {
	mi := &file_continuoustracking_v1_tracking_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrailPoint.ProtoReflect.Descriptor instead.
func (*TrailPoint) Descriptor() ([]byte, []int) {
	return file_continuoustracking_v1_tracking_proto_rawDescGZIP(), []int{4}
}

func (x *TrailPoint) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *TrailPoint) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

// PosteriorEvidence captures the identity resolver's confidence snapshot.
type PosteriorEvidence struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TopProb        float32                `protobuf:"fixed32,1,opt,name=top_prob,json=topProb,proto3" json:"top_prob,omitempty"`                       // P(top identity | observations)
	Top2Prob       float32                `protobuf:"fixed32,2,opt,name=top2_prob,json=top2Prob,proto3" json:"top2_prob,omitempty"`                    // P(second-best identity | observations)
	FaceAnchorUsed bool                   `protobuf:"varint,3,opt,name=face_anchor_used,json=faceAnchorUsed,proto3" json:"face_anchor_used,omitempty"` // true when a face anchor drove the commit
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PosteriorEvidence) Reset() {
	*x = PosteriorEvidence{}
	mi := &file_continuoustracking_v1_tracking_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PosteriorEvidence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PosteriorEvidence) ProtoMessage() {}

func (x *PosteriorEvidence) ProtoReflect() protoreflect.Message {
	mi := &file_continuoustracking_v1_tracking_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PosteriorEvidence.ProtoReflect.Descriptor instead.
func (*PosteriorEvidence) Descriptor() ([]byte, []int) {
	return file_continuoustracking_v1_tracking_proto_rawDescGZIP(), []int{5}
}

func (x *PosteriorEvidence) GetTopProb() float32 {
	if x != nil {
		return x.TopProb
	}
	return 0
}

func (x *PosteriorEvidence) GetTop2Prob() float32 {
	if x != nil {
		return x.Top2Prob
	}
	return 0
}

func (x *PosteriorEvidence) GetFaceAnchorUsed() bool {
	if x != nil {
		return x.FaceAnchorUsed
	}
	return false
}

// BoundingBox in pixel coordinates: top-left origin, width/height positive.
type BoundingBox struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	XMin          int32                  `protobuf:"varint,1,opt,name=x_min,json=xMin,proto3" json:"x_min,omitempty"`
	YMin          int32                  `protobuf:"varint,2,opt,name=y_min,json=yMin,proto3" json:"y_min,omitempty"`
	XMax          int32                  `protobuf:"varint,3,opt,name=x_max,json=xMax,proto3" json:"x_max,omitempty"`
	YMax          int32                  `protobuf:"varint,4,opt,name=y_max,json=yMax,proto3" json:"y_max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoundingBox) Reset() {
	*x = BoundingBox{}
	mi := &file_continuoustracking_v1_tracking_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoundingBox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoundingBox) ProtoMessage() {}

func (x *BoundingBox) ProtoReflect() protoreflect.Message {
	mi := &file_continuoustracking_v1_tracking_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoundingBox.ProtoReflect.Descriptor instead.
func (*BoundingBox) Descriptor() ([]byte, []int) {
	return file_continuoustracking_v1_tracking_proto_rawDescGZIP(), []int{6}
}

func (x *BoundingBox) GetXMin() int32 {
	if x != nil {
		return x.XMin
	}
	return 0
}

func (x *BoundingBox) GetYMin() int32 {
	if x != nil {
		return x.YMin
	}
	return 0
}

func (x *BoundingBox) GetXMax() int32 {
	if x != nil {
		return x.XMax
	}
	return 0
}

func (x *BoundingBox) GetYMax() int32 {
	if x != nil {
		return x.YMax
	}
	return 0
}

// FloorPoint is a 2D point in the shared floor-plan coordinate system, in
// millimetres.  When calibrated=true the coordinates are consistent across
// all cameras that share the same floor_plan_id.  When calibrated=false
// both coordinates are zero and must not be used for metric comparisons.
type FloorPoint struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// X coordinate in the shared floor-plan frame, in mm.
	XMm int64 `protobuf:"varint,1,opt,name=x_mm,json=xMm,proto3" json:"x_mm,omitempty"`
	// Y coordinate in the shared floor-plan frame, in mm.
	YMm int64 `protobuf:"varint,2,opt,name=y_mm,json=yMm,proto3" json:"y_mm,omitempty"`
	// Whether the homography was calibrated for the source camera.
	Calibrated    bool `protobuf:"varint,3,opt,name=calibrated,proto3" json:"calibrated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FloorPoint) Reset() {
	*x = FloorPoint{}
	mi := &file_continuoustracking_v1_tracking_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FloorPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FloorPoint) ProtoMessage() {}

func (x *FloorPoint) ProtoReflect() protoreflect.Message {
	mi := &file_continuoustracking_v1_tracking_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FloorPoint.ProtoReflect.Descriptor instead.
func (*FloorPoint) Descriptor() ([]byte, []int) {
	return file_continuoustracking_v1_tracking_proto_rawDescGZIP(), []int{7}
}

func (x *FloorPoint) GetXMm() int64 {
	if x != nil {
		return x.XMm
	}
	return 0
}

func (x *FloorPoint) GetYMm() int64 {
	if x != nil {
		return x.YMm
	}
	return 0
}

func (x *FloorPoint) GetCalibrated() bool {
	if x != nil {
		return x.Calibrated
	}
	return false
}

// IdentityRevision is published to the tracking.revisions Redis Stream
// when an identity assignment for a Person Hypothesis changes.
// N0: renamed global_track_id -> ph_id; tracklet_ids reserved.
type IdentityRevision struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Person Hypothesis whose identity is being revised.
	PhId string `protobuf:"bytes,1,opt,name=ph_id,json=phId,proto3" json:"ph_id,omitempty"`
	// Probability distribution over candidate identities.
	// N0: unused by the PH-native revision; kept for wire compatibility.
	Candidates []*IdentityCandidate `protobuf:"bytes,2,rep,name=candidates,proto3" json:"candidates,omitempty"`
	// The MAP (maximum a posteriori) estimate.
	// N0: unused; kept for wire compatibility.
	MapIdentityId string `protobuf:"bytes,3,opt,name=map_identity_id,json=mapIdentityId,proto3" json:"map_identity_id,omitempty"`
	// Entropy of the posterior (measure of uncertainty, in bits).
	// Lower = more certain.
	// N0: unused at this field; posterior_entropy moved into evidence_json.
	PosteriorEntropy float32 `protobuf:"fixed32,4,opt,name=posterior_entropy,json=posteriorEntropy,proto3" json:"posterior_entropy,omitempty"`
	// When this revision was computed.
	RevisionTimeUnixNs uint64 `protobuf:"fixed64,5,opt,name=revision_time_unix_ns,json=revisionTimeUnixNs,proto3" json:"revision_time_unix_ns,omitempty"`
	// Unique ID of this revision. Used for idempotent CC-side rewrites.
	RevisionId string `protobuf:"bytes,6,opt,name=revision_id,json=revisionId,proto3" json:"revision_id,omitempty"`
	// Identity before the revision (empty when promoting from UNKNOWN).
	PreviousIdentityId string `protobuf:"bytes,8,opt,name=previous_identity_id,json=previousIdentityId,proto3" json:"previous_identity_id,omitempty"`
	// Identity after the revision (empty when demoting to UNKNOWN).
	NewIdentityId string `protobuf:"bytes,9,opt,name=new_identity_id,json=newIdentityId,proto3" json:"new_identity_id,omitempty"`
	// Human-readable reason: initial_assignment | identity_change |
	// demoted_to_unknown | manual_override | merge.
	Reason string `protobuf:"bytes,10,opt,name=reason,proto3" json:"reason,omitempty"`
	// N0: evidence_json extended with actor, rewritten_rows, observation_count,
	// and evidence_sources in addition to the legacy posterior fields.
	EvidenceJson string `protobuf:"bytes,11,opt,name=evidence_json,json=evidenceJson,proto3" json:"evidence_json,omitempty"`
	// Explicit inferred identity from the resolver.
	InferredIdentityId string `protobuf:"bytes,12,opt,name=inferred_identity_id,json=inferredIdentityId,proto3" json:"inferred_identity_id,omitempty"`
	// Effective identity after applying overrides and authority rules.
	EffectiveIdentityId string `protobuf:"bytes,13,opt,name=effective_identity_id,json=effectiveIdentityId,proto3" json:"effective_identity_id,omitempty"`
	// Authority level (e.g. "face", "reid", "operator").
	Authority string `protobuf:"bytes,14,opt,name=authority,proto3" json:"authority,omitempty"`
	// Component or user that produced the decision.
	DecisionSource string `protobuf:"bytes,15,opt,name=decision_source,json=decisionSource,proto3" json:"decision_source,omitempty"`
	// The durable UUID for this specific decision.
	DecisionId string `protobuf:"bytes,16,opt,name=decision_id,json=decisionId,proto3" json:"decision_id,omitempty"`
	// Description of any conflict (e.g. duplicate active identity).
	Conflict string `protobuf:"bytes,17,opt,name=conflict,proto3" json:"conflict,omitempty"`
	// Operator/inferred revision kind: operator_correction | operator_unknown |
	// operator_frame_correction | operator_handoff | operator_compensation |
	// inferred. Empty for legacy automatic revisions.
	RevisionKind string `protobuf:"bytes,18,opt,name=revision_kind,json=revisionKind,proto3" json:"revision_kind,omitempty"`
	// Effective range this revision applies to (operator authority is bounded to
	// these observation timestamps). Zero when the revision is not range-scoped.
	RangeStartUnixNs uint64 `protobuf:"fixed64,19,opt,name=range_start_unix_ns,json=rangeStartUnixNs,proto3" json:"range_start_unix_ns,omitempty"`
	RangeEndUnixNs   uint64 `protobuf:"fixed64,20,opt,name=range_end_unix_ns,json=rangeEndUnixNs,proto3" json:"range_end_unix_ns,omitempty"`
	// Authority of the effective range: "operator" or "inferred".
	RangeAuthority string `protobuf:"bytes,21,opt,name=range_authority,json=rangeAuthority,proto3" json:"range_authority,omitempty"`
	// Stable IDs for the revision-range projection model.
	RevisionRangeId string `protobuf:"bytes,22,opt,name=revision_range_id,json=revisionRangeId,proto3" json:"revision_range_id,omitempty"`
	CorrectionId    string `protobuf:"bytes,23,opt,name=correction_id,json=correctionId,proto3" json:"correction_id,omitempty"`
	// Projections that must acknowledge this revision_id before the correction
	// job is complete (e.g. "cts_internal", "cc").
	RequiredProjections []string `protobuf:"bytes,24,rep,name=required_projections,json=requiredProjections,proto3" json:"required_projections,omitempty"`
	// Schema version of the revision-range payload for forward compatibility.
	RevisionSchemaVersion string `protobuf:"bytes,25,opt,name=revision_schema_version,json=revisionSchemaVersion,proto3" json:"revision_schema_version,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *IdentityRevision) Reset() {
	*x = IdentityRevision{}
	mi := &file_continuoustracking_v1_tracking_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityRevision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityRevision) ProtoMessage() {}

func (x *IdentityRevision) ProtoReflect() protoreflect.Message {
	mi := &file_continuoustracking_v1_tracking_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityRevision.ProtoReflect.Descriptor instead.
func (*IdentityRevision) Descriptor() ([]byte, []int) {
	return file_continuoustracking_v1_tracking_proto_rawDescGZIP(), []int{8}
}

func (x *IdentityRevision) GetPhId() string {
	if x != nil {
		return x.PhId
	}
	return ""
}

func (x *IdentityRevision) GetCandidates() []*IdentityCandidate {
	if x != nil {
		return x.Candidates
	}
	return nil
}

func (x *IdentityRevision) GetMapIdentityId() string {
	if x != nil {
		return x.MapIdentityId
	}
	return ""
}

func (x *IdentityRevision) GetPosteriorEntropy() float32 {
	if x != nil {
		return x.PosteriorEntropy
	}
	return 0
}

func (x *IdentityRevision) GetRevisionTimeUnixNs() uint64 {
	if x != nil {
		return x.RevisionTimeUnixNs
	}
	return 0
}

func (x *IdentityRevision) GetRevisionId() string {
	if x != nil {
		return x.RevisionId
	}
	return ""
}

func (x *IdentityRevision) GetPreviousIdentityId() string {
	if x != nil {
		return x.PreviousIdentityId
	}
	return ""
}

func (x *IdentityRevision) GetNewIdentityId() string {
	if x != nil {
		return x.NewIdentityId
	}
	return ""
}

func (x *IdentityRevision) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *IdentityRevision) GetEvidenceJson() string {
	if x != nil {
		return x.EvidenceJson
	}
	return ""
}

func (x *IdentityRevision) GetInferredIdentityId() string {
	if x != nil {
		return x.InferredIdentityId
	}
	return ""
}

func (x *IdentityRevision) GetEffectiveIdentityId() string {
	if x != nil {
		return x.EffectiveIdentityId
	}
	return ""
}

func (x *IdentityRevision) GetAuthority() string {
	if x != nil {
		return x.Authority
	}
	return ""
}

func (x *IdentityRevision) GetDecisionSource() string {
	if x != nil {
		return x.DecisionSource
	}
	return ""
}

func (x *IdentityRevision) GetDecisionId() string {
	if x != nil {
		return x.DecisionId
	}
	return ""
}

func (x *IdentityRevision) GetConflict() string {
	if x != nil {
		return x.Conflict
	}
	return ""
}

func (x *IdentityRevision) GetRevisionKind() string {
	if x != nil {
		return x.RevisionKind
	}
	return ""
}

func (x *IdentityRevision) GetRangeStartUnixNs() uint64 {
	if x != nil {
		return x.RangeStartUnixNs
	}
	return 0
}

func (x *IdentityRevision) GetRangeEndUnixNs() uint64 {
	if x != nil {
		return x.RangeEndUnixNs
	}
	return 0
}

func (x *IdentityRevision) GetRangeAuthority() string {
	if x != nil {
		return x.RangeAuthority
	}
	return ""
}

func (x *IdentityRevision) GetRevisionRangeId() string {
	if x != nil {
		return x.RevisionRangeId
	}
	return ""
}

func (x *IdentityRevision) GetCorrectionId() string {
	if x != nil {
		return x.CorrectionId
	}
	return ""
}

func (x *IdentityRevision) GetRequiredProjections() []string {
	if x != nil {
		return x.RequiredProjections
	}
	return nil
}

func (x *IdentityRevision) GetRevisionSchemaVersion() string {
	if x != nil {
		return x.RevisionSchemaVersion
	}
	return ""
}

// IdentitySnapshot is a lightweight per-PH identity state for live
// display.  Unlike IdentityRevision, it is not a standalone stream message —
// it only appears as a sub-message of TrackingEvent.
type IdentitySnapshot struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// R3: canonical field name.  Field number 1 is unchanged; binary wire is
	// compatible.  The old name "global_track_id" is reserved to prevent
	// accidental JSON/text-format reuse.
	PhId string `protobuf:"bytes,1,opt,name=ph_id,json=phId,proto3" json:"ph_id,omitempty"`
	// The committed identity for this global track (empty when UNKNOWN).
	IdentityId string `protobuf:"bytes,2,opt,name=identity_id,json=identityId,proto3" json:"identity_id,omitempty"`
	// Probability of the top identity from the posterior.
	TopProbability float32 `protobuf:"fixed32,3,opt,name=top_probability,json=topProbability,proto3" json:"top_probability,omitempty"`
	// Probability of the second-best identity from the posterior.
	SecondProbability float32 `protobuf:"fixed32,4,opt,name=second_probability,json=secondProbability,proto3" json:"second_probability,omitempty"`
	// Entropy of the full posterior (bits). Lower = more certain.
	PosteriorEntropy float32 `protobuf:"fixed32,5,opt,name=posterior_entropy,json=posteriorEntropy,proto3" json:"posterior_entropy,omitempty"`
	// Whether direct face evidence (ArcFace) contributed to this decision.
	DirectFaceEvidence bool `protobuf:"varint,6,opt,name=direct_face_evidence,json=directFaceEvidence,proto3" json:"direct_face_evidence,omitempty"`
	// Evidence source summary serialised as JSON:
	// {"sources": {"direct_face": 1, "reid": 3}, "direct_face_confidence": 0.95, ...}
	EvidenceJson string `protobuf:"bytes,7,opt,name=evidence_json,json=evidenceJson,proto3" json:"evidence_json,omitempty"`
	// Exponential moving average of crop-quality scores for this PH (U1/U2).
	// Range [0, 1]; 0.0 means no quality data yet.  Consumed by CC to populate
	// PersonLocationEnvelope.quality without client-side inference (design rule D5).
	MeanQuality float32 `protobuf:"fixed32,8,opt,name=mean_quality,json=meanQuality,proto3" json:"mean_quality,omitempty"`
	// Explicit inferred identity from the resolver.
	InferredIdentityId string `protobuf:"bytes,9,opt,name=inferred_identity_id,json=inferredIdentityId,proto3" json:"inferred_identity_id,omitempty"`
	// Effective identity after applying overrides and authority rules.
	EffectiveIdentityId string `protobuf:"bytes,10,opt,name=effective_identity_id,json=effectiveIdentityId,proto3" json:"effective_identity_id,omitempty"`
	// Authority level (e.g. "face", "reid", "operator").
	Authority string `protobuf:"bytes,11,opt,name=authority,proto3" json:"authority,omitempty"`
	// Component or user that produced the decision.
	DecisionSource string `protobuf:"bytes,12,opt,name=decision_source,json=decisionSource,proto3" json:"decision_source,omitempty"`
	// The durable UUID for this specific decision.
	DecisionId string `protobuf:"bytes,13,opt,name=decision_id,json=decisionId,proto3" json:"decision_id,omitempty"`
	// Description of any conflict.
	Conflict string `protobuf:"bytes,14,opt,name=conflict,proto3" json:"conflict,omitempty"`
	// Timestamp of the last independent authoritative evidence.
	LastIndependentEvidenceAtUnixNs uint64 `protobuf:"fixed64,15,opt,name=last_independent_evidence_at_unix_ns,json=lastIndependentEvidenceAtUnixNs,proto3" json:"last_independent_evidence_at_unix_ns,omitempty"`
	// Hash of the configuration used for the resolver.
	ConfigHash string `protobuf:"bytes,16,opt,name=config_hash,json=configHash,proto3" json:"config_hash,omitempty"`
	// Version of the model set used for ReID/Face/etc.
	ModelSetVersion string `protobuf:"bytes,17,opt,name=model_set_version,json=modelSetVersion,proto3" json:"model_set_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *IdentitySnapshot) Reset() {
	*x = IdentitySnapshot{}
	mi := &file_continuoustracking_v1_tracking_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentitySnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentitySnapshot) ProtoMessage() {}

func (x *IdentitySnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_continuoustracking_v1_tracking_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentitySnapshot.ProtoReflect.Descriptor instead.
func (*IdentitySnapshot) Descriptor() ([]byte, []int) {
	return file_continuoustracking_v1_tracking_proto_rawDescGZIP(), []int{9}
}

func (x *IdentitySnapshot) GetPhId() string {
	if x != nil {
		return x.PhId
	}
	return ""
}

func (x *IdentitySnapshot) GetIdentityId() string {
	if x != nil {
		return x.IdentityId
	}
	return ""
}

func (x *IdentitySnapshot) GetTopProbability() float32 {
	if x != nil {
		return x.TopProbability
	}
	return 0
}

func (x *IdentitySnapshot) GetSecondProbability() float32 {
	if x != nil {
		return x.SecondProbability
	}
	return 0
}

func (x *IdentitySnapshot) GetPosteriorEntropy() float32 {
	if x != nil {
		return x.PosteriorEntropy
	}
	return 0
}

func (x *IdentitySnapshot) GetDirectFaceEvidence() bool {
	if x != nil {
		return x.DirectFaceEvidence
	}
	return false
}

func (x *IdentitySnapshot) GetEvidenceJson() string {
	if x != nil {
		return x.EvidenceJson
	}
	return ""
}

func (x *IdentitySnapshot) GetMeanQuality() float32 {
	if x != nil {
		return x.MeanQuality
	}
	return 0
}

func (x *IdentitySnapshot) GetInferredIdentityId() string {
	if x != nil {
		return x.InferredIdentityId
	}
	return ""
}

func (x *IdentitySnapshot) GetEffectiveIdentityId() string {
	if x != nil {
		return x.EffectiveIdentityId
	}
	return ""
}

func (x *IdentitySnapshot) GetAuthority() string {
	if x != nil {
		return x.Authority
	}
	return ""
}

func (x *IdentitySnapshot) GetDecisionSource() string {
	if x != nil {
		return x.DecisionSource
	}
	return ""
}

func (x *IdentitySnapshot) GetDecisionId() string {
	if x != nil {
		return x.DecisionId
	}
	return ""
}

func (x *IdentitySnapshot) GetConflict() string {
	if x != nil {
		return x.Conflict
	}
	return ""
}

func (x *IdentitySnapshot) GetLastIndependentEvidenceAtUnixNs() uint64 {
	if x != nil {
		return x.LastIndependentEvidenceAtUnixNs
	}
	return 0
}

func (x *IdentitySnapshot) GetConfigHash() string {
	if x != nil {
		return x.ConfigHash
	}
	return ""
}

func (x *IdentitySnapshot) GetModelSetVersion() string {
	if x != nil {
		return x.ModelSetVersion
	}
	return ""
}

// IdentityCandidate is one candidate identity with its posterior probability.
type IdentityCandidate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The identity's gallery entry ID.
	IdentityId string `protobuf:"bytes,1,opt,name=identity_id,json=identityId,proto3" json:"identity_id,omitempty"`
	// Display name for the identity.
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Posterior probability P(identity | observations).
	Probability   float32 `protobuf:"fixed32,3,opt,name=probability,proto3" json:"probability,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentityCandidate) Reset() {
	*x = IdentityCandidate{}
	mi := &file_continuoustracking_v1_tracking_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityCandidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityCandidate) ProtoMessage() {}

func (x *IdentityCandidate) ProtoReflect() protoreflect.Message {
	mi := &file_continuoustracking_v1_tracking_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityCandidate.ProtoReflect.Descriptor instead.
func (*IdentityCandidate) Descriptor() ([]byte, []int) {
	return file_continuoustracking_v1_tracking_proto_rawDescGZIP(), []int{10}
}

func (x *IdentityCandidate) GetIdentityId() string {
	if x != nil {
		return x.IdentityId
	}
	return ""
}

func (x *IdentityCandidate) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *IdentityCandidate) GetProbability() float32 {
	if x != nil {
		return x.Probability
	}
	return 0
}

// PresenceEvent is published to tracking.presence when a person appears in
// or disappears from the home.  One event per state transition; never
// emitted per frame.
type PresenceEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Person Hypothesis ID of the person whose presence changed.
	PhId string `protobuf:"bytes,1,opt,name=ph_id,json=phId,proto3" json:"ph_id,omitempty"`
	// Committed identity ID (empty when the PH is still UNKNOWN).
	IdentityId string `protobuf:"bytes,2,opt,name=identity_id,json=identityId,proto3" json:"identity_id,omitempty"`
	// Whether the person appeared or disappeared.
	EventType PresenceEventType `protobuf:"varint,3,opt,name=event_type,json=eventType,proto3,enum=continuoustracking.v1.PresenceEventType" json:"event_type,omitempty"`
	// Room where the event occurred (camera-bound room at the time).
	RoomName string `protobuf:"bytes,4,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	// Wall-clock time of the state change.
	EventTimeUnixNs uint64 `protobuf:"fixed64,5,opt,name=event_time_unix_ns,json=eventTimeUnixNs,proto3" json:"event_time_unix_ns,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PresenceEvent) Reset() {
	*x = PresenceEvent{}
	mi := &file_continuoustracking_v1_tracking_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresenceEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresenceEvent) ProtoMessage() {}

func (x *PresenceEvent) ProtoReflect() protoreflect.Message {
	mi := &file_continuoustracking_v1_tracking_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresenceEvent.ProtoReflect.Descriptor instead.
func (*PresenceEvent) Descriptor() ([]byte, []int) {
	return file_continuoustracking_v1_tracking_proto_rawDescGZIP(), []int{11}
}

func (x *PresenceEvent) GetPhId() string {
	if x != nil {
		return x.PhId
	}
	return ""
}

func (x *PresenceEvent) GetIdentityId() string {
	if x != nil {
		return x.IdentityId
	}
	return ""
}

func (x *PresenceEvent) GetEventType() PresenceEventType {
	if x != nil {
		return x.EventType
	}
	return PresenceEventType_PRESENCE_EVENT_TYPE_UNSPECIFIED
}

func (x *PresenceEvent) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *PresenceEvent) GetEventTimeUnixNs() uint64 {
	if x != nil {
		return x.EventTimeUnixNs
	}
	return 0
}

// DwellEvent is published to tracking.dwell when a dwell segment starts
// or ends (person enters or leaves a room).  One event per threshold
// crossing; never emitted per frame.
type DwellEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Person Hypothesis ID.
	PhId string `protobuf:"bytes,1,opt,name=ph_id,json=phId,proto3" json:"ph_id,omitempty"`
	// Committed identity ID (empty when UNKNOWN).
	IdentityId string `protobuf:"bytes,2,opt,name=identity_id,json=identityId,proto3" json:"identity_id,omitempty"`
	// Whether the dwell started or ended.
	EventType DwellEventType `protobuf:"varint,3,opt,name=event_type,json=eventType,proto3,enum=continuoustracking.v1.DwellEventType" json:"event_type,omitempty"`
	// Room name of the dwell segment.
	RoomName string `protobuf:"bytes,4,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	// Wall-clock time of the state change.
	EventTimeUnixNs uint64 `protobuf:"fixed64,5,opt,name=event_time_unix_ns,json=eventTimeUnixNs,proto3" json:"event_time_unix_ns,omitempty"`
	// Duration in seconds (populated only on ended events).
	DurationS     int32 `protobuf:"varint,6,opt,name=duration_s,json=durationS,proto3" json:"duration_s,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DwellEvent) Reset() {
	*x = DwellEvent{}
	mi := &file_continuoustracking_v1_tracking_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DwellEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DwellEvent) ProtoMessage() {}

func (x *DwellEvent) ProtoReflect() protoreflect.Message {
	mi := &file_continuoustracking_v1_tracking_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DwellEvent.ProtoReflect.Descriptor instead.
func (*DwellEvent) Descriptor() ([]byte, []int) {
	return file_continuoustracking_v1_tracking_proto_rawDescGZIP(), []int{12}
}

func (x *DwellEvent) GetPhId() string {
	if x != nil {
		return x.PhId
	}
	return ""
}

func (x *DwellEvent) GetIdentityId() string {
	if x != nil {
		return x.IdentityId
	}
	return ""
}

func (x *DwellEvent) GetEventType() DwellEventType {
	if x != nil {
		return x.EventType
	}
	return DwellEventType_DWELL_EVENT_TYPE_UNSPECIFIED
}

func (x *DwellEvent) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *DwellEvent) GetEventTimeUnixNs() uint64 {
	if x != nil {
		return x.EventTimeUnixNs
	}
	return 0
}

func (x *DwellEvent) GetDurationS() int32 {
	if x != nil {
		return x.DurationS
	}
	return 0
}

// CCIdentityAssertion represents an identity assertion generated by Cognitive Companion.
// This replaces the old legacy text-based payload on the cc.identity_assertions stream.
type CCIdentityAssertion struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The identity assigned by CC.
	PersonId string `protobuf:"bytes,1,opt,name=person_id,json=personId,proto3" json:"person_id,omitempty"`
	// The camera from which this assertion originates.
	CameraId string `protobuf:"bytes,2,opt,name=camera_id,json=cameraId,proto3" json:"camera_id,omitempty"`
	// When the frame was captured.
	CapturedAtUnixNs uint64 `protobuf:"fixed64,3,opt,name=captured_at_unix_ns,json=capturedAtUnixNs,proto3" json:"captured_at_unix_ns,omitempty"`
	// Estimated physical floor position (X) in meters.
	FloorXM float32 `protobuf:"fixed32,4,opt,name=floor_x_m,json=floorXM,proto3" json:"floor_x_m,omitempty"`
	// Estimated physical floor position (Y) in meters.
	FloorYM float32 `protobuf:"fixed32,5,opt,name=floor_y_m,json=floorYM,proto3" json:"floor_y_m,omitempty"`
	// Raw cosine similarity from the face ID service.
	RawSimilarity float32 `protobuf:"fixed32,6,opt,name=raw_similarity,json=rawSimilarity,proto3" json:"raw_similarity,omitempty"`
	// Calibrated confidence, if calibration is enabled.
	CalibratedConfidence *float32 `protobuf:"fixed32,7,opt,name=calibrated_confidence,json=calibratedConfidence,proto3,oneof" json:"calibrated_confidence,omitempty"`
	// Status of the calibration ("calibrated", "uncalibrated", "extrapolated").
	CalibrationStatus string `protobuf:"bytes,8,opt,name=calibration_status,json=calibrationStatus,proto3" json:"calibration_status,omitempty"`
	// The component that generated this assertion (e.g., "cc-arcface").
	Source string `protobuf:"bytes,9,opt,name=source,proto3" json:"source,omitempty"`
	// Which model version was used.
	ModelVersion string `protobuf:"bytes,10,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	// Which preprocessing version was used.
	PreprocessingVersion string `protobuf:"bytes,11,opt,name=preprocessing_version,json=preprocessingVersion,proto3" json:"preprocessing_version,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CCIdentityAssertion) Reset() {
	*x = CCIdentityAssertion{}
	mi := &file_continuoustracking_v1_tracking_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CCIdentityAssertion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CCIdentityAssertion) ProtoMessage() {}

func (x *CCIdentityAssertion) ProtoReflect() protoreflect.Message {
	mi := &file_continuoustracking_v1_tracking_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CCIdentityAssertion.ProtoReflect.Descriptor instead.
func (*CCIdentityAssertion) Descriptor() ([]byte, []int) {
	return file_continuoustracking_v1_tracking_proto_rawDescGZIP(), []int{13}
}

func (x *CCIdentityAssertion) GetPersonId() string {
	if x != nil {
		return x.PersonId
	}
	return ""
}

func (x *CCIdentityAssertion) GetCameraId() string {
	if x != nil {
		return x.CameraId
	}
	return ""
}

func (x *CCIdentityAssertion) GetCapturedAtUnixNs() uint64 {
	if x != nil {
		return x.CapturedAtUnixNs
	}
	return 0
}

func (x *CCIdentityAssertion) GetFloorXM() float32 {
	if x != nil {
		return x.FloorXM
	}
	return 0
}

func (x *CCIdentityAssertion) GetFloorYM() float32 {
	if x != nil {
		return x.FloorYM
	}
	return 0
}

func (x *CCIdentityAssertion) GetRawSimilarity() float32 {
	if x != nil {
		return x.RawSimilarity
	}
	return 0
}

func (x *CCIdentityAssertion) GetCalibratedConfidence() float32 {
	if x != nil && x.CalibratedConfidence != nil {
		return *x.CalibratedConfidence
	}
	return 0
}

func (x *CCIdentityAssertion) GetCalibrationStatus() string {
	if x != nil {
		return x.CalibrationStatus
	}
	return ""
}

func (x *CCIdentityAssertion) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *CCIdentityAssertion) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

func (x *CCIdentityAssertion) GetPreprocessingVersion() string {
	if x != nil {
		return x.PreprocessingVersion
	}
	return ""
}

var File_continuoustracking_v1_tracking_proto protoreflect.FileDescriptor

const file_continuoustracking_v1_tracking_proto_rawDesc = "" +
	"\n" +
	"$continuoustracking/v1/tracking.proto\x12\x15continuoustracking.v1\"\xc5\x03\n" +
	"\rTrackingEvent\x12\x1b\n" +
	"\tcamera_id\x18\x01 \x01(\tR\bcameraId\x12+\n" +
	"\x12event_time_unix_ns\x18\x02 \x01(\x06R\x0feventTimeUnixNs\x12<\n" +
	"\tframe_ref\x18\x03 \x01(\v2\x1f.continuoustracking.v1.FrameRefR\bframeRef\x12@\n" +
	"\n" +
	"detections\x18\x04 \x03(\v2 .continuoustracking.v1.DetectionR\n" +
	"detections\x12Z\n" +
	"\x12identity_revisions\x18\x05 \x03(\v2'.continuoustracking.v1.IdentityRevisionB\x02\x18\x01R\x11identityRevisions\x12\x1b\n" +
	"\troom_name\x18\x06 \x01(\tR\broomName\x12\x19\n" +
	"\bevent_id\x18\a \x01(\tR\aeventId\x12V\n" +
	"\x12identity_snapshots\x18\b \x03(\v2'.continuoustracking.v1.IdentitySnapshotR\x11identitySnapshots\"\xa7\x01\n" +
	"\bFrameRef\x12\x1b\n" +
	"\tminio_key\x18\x01 \x01(\tR\bminioKey\x12\x14\n" +
	"\x05width\x18\x02 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x05R\x06height\x12\x1f\n" +
	"\vframe_index\x18\x04 \x01(\x03R\n" +
	"frameIndex\x12/\n" +
	"\x14capture_time_unix_ns\x18\x05 \x01(\x06R\x11captureTimeUnixNs\"\xbe\x04\n" +
	"\tDetection\x12!\n" +
	"\fdetection_id\x18\x01 \x01(\tR\vdetectionId\x126\n" +
	"\x04bbox\x18\x02 \x01(\v2\".continuoustracking.v1.BoundingBoxR\x04bbox\x12\x1c\n" +
	"\tembedding\x18\x03 \x03(\x02R\tembedding\x12\x1e\n" +
	"\n" +
	"confidence\x18\x04 \x01(\x02R\n" +
	"confidence\x12B\n" +
	"\vfloor_point\x18\a \x01(\v2!.continuoustracking.v1.FloorPointR\n" +
	"floorPoint\x12J\n" +
	"\x0epose_keypoints\x18\t \x03(\v2#.continuoustracking.v1.PoseKeypointR\rposeKeypoints\x127\n" +
	"\x05trail\x18\n" +
	" \x03(\v2!.continuoustracking.v1.TrailPointR\x05trail\x12D\n" +
	"\bevidence\x18\v \x01(\v2(.continuoustracking.v1.PosteriorEvidenceR\bevidence\x12\x17\n" +
	"\afloor_x\x18\f \x01(\x02R\x06floorX\x12\x17\n" +
	"\afloor_y\x18\r \x01(\x02R\x06floorY\x12\x18\n" +
	"\aposture\x18\x0e \x01(\tR\aposture\x12\x13\n" +
	"\x05ph_id\x18\x0f \x01(\tR\x04phIdJ\x04\b\x05\x10\x06J\x04\b\x06\x10\aR\vtracklet_idR\x0fglobal_track_id\"@\n" +
	"\fPoseKeypoint\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x02R\x05score\"(\n" +
	"\n" +
	"TrailPoint\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\"u\n" +
	"\x11PosteriorEvidence\x12\x19\n" +
	"\btop_prob\x18\x01 \x01(\x02R\atopProb\x12\x1b\n" +
	"\ttop2_prob\x18\x02 \x01(\x02R\btop2Prob\x12(\n" +
	"\x10face_anchor_used\x18\x03 \x01(\bR\x0efaceAnchorUsed\"a\n" +
	"\vBoundingBox\x12\x13\n" +
	"\x05x_min\x18\x01 \x01(\x05R\x04xMin\x12\x13\n" +
	"\x05y_min\x18\x02 \x01(\x05R\x04yMin\x12\x13\n" +
	"\x05x_max\x18\x03 \x01(\x05R\x04xMax\x12\x13\n" +
	"\x05y_max\x18\x04 \x01(\x05R\x04yMax\"R\n" +
	"\n" +
	"FloorPoint\x12\x11\n" +
	"\x04x_mm\x18\x01 \x01(\x03R\x03xMm\x12\x11\n" +
	"\x04y_mm\x18\x02 \x01(\x03R\x03yMm\x12\x1e\n" +
	"\n" +
	"calibrated\x18\x03 \x01(\bR\n" +
	"calibrated\"\x85\b\n" +
	"\x10IdentityRevision\x12\x13\n" +
	"\x05ph_id\x18\x01 \x01(\tR\x04phId\x12H\n" +
	"\n" +
	"candidates\x18\x02 \x03(\v2(.continuoustracking.v1.IdentityCandidateR\n" +
	"candidates\x12&\n" +
	"\x0fmap_identity_id\x18\x03 \x01(\tR\rmapIdentityId\x12+\n" +
	"\x11posterior_entropy\x18\x04 \x01(\x02R\x10posteriorEntropy\x121\n" +
	"\x15revision_time_unix_ns\x18\x05 \x01(\x06R\x12revisionTimeUnixNs\x12\x1f\n" +
	"\vrevision_id\x18\x06 \x01(\tR\n" +
	"revisionId\x120\n" +
	"\x14previous_identity_id\x18\b \x01(\tR\x12previousIdentityId\x12&\n" +
	"\x0fnew_identity_id\x18\t \x01(\tR\rnewIdentityId\x12\x16\n" +
	"\x06reason\x18\n" +
	" \x01(\tR\x06reason\x12#\n" +
	"\revidence_json\x18\v \x01(\tR\fevidenceJson\x120\n" +
	"\x14inferred_identity_id\x18\f \x01(\tR\x12inferredIdentityId\x122\n" +
	"\x15effective_identity_id\x18\r \x01(\tR\x13effectiveIdentityId\x12\x1c\n" +
	"\tauthority\x18\x0e \x01(\tR\tauthority\x12'\n" +
	"\x0fdecision_source\x18\x0f \x01(\tR\x0edecisionSource\x12\x1f\n" +
	"\vdecision_id\x18\x10 \x01(\tR\n" +
	"decisionId\x12\x1a\n" +
	"\bconflict\x18\x11 \x01(\tR\bconflict\x12#\n" +
	"\rrevision_kind\x18\x12 \x01(\tR\frevisionKind\x12-\n" +
	"\x13range_start_unix_ns\x18\x13 \x01(\x06R\x10rangeStartUnixNs\x12)\n" +
	"\x11range_end_unix_ns\x18\x14 \x01(\x06R\x0erangeEndUnixNs\x12'\n" +
	"\x0frange_authority\x18\x15 \x01(\tR\x0erangeAuthority\x12*\n" +
	"\x11revision_range_id\x18\x16 \x01(\tR\x0frevisionRangeId\x12#\n" +
	"\rcorrection_id\x18\x17 \x01(\tR\fcorrectionId\x121\n" +
	"\x14required_projections\x18\x18 \x03(\tR\x13requiredProjections\x126\n" +
	"\x17revision_schema_version\x18\x19 \x01(\tR\x15revisionSchemaVersionJ\x04\b\a\x10\b\"\xde\x05\n" +
	"\x10IdentitySnapshot\x12\x13\n" +
	"\x05ph_id\x18\x01 \x01(\tR\x04phId\x12\x1f\n" +
	"\videntity_id\x18\x02 \x01(\tR\n" +
	"identityId\x12'\n" +
	"\x0ftop_probability\x18\x03 \x01(\x02R\x0etopProbability\x12-\n" +
	"\x12second_probability\x18\x04 \x01(\x02R\x11secondProbability\x12+\n" +
	"\x11posterior_entropy\x18\x05 \x01(\x02R\x10posteriorEntropy\x120\n" +
	"\x14direct_face_evidence\x18\x06 \x01(\bR\x12directFaceEvidence\x12#\n" +
	"\revidence_json\x18\a \x01(\tR\fevidenceJson\x12!\n" +
	"\fmean_quality\x18\b \x01(\x02R\vmeanQuality\x120\n" +
	"\x14inferred_identity_id\x18\t \x01(\tR\x12inferredIdentityId\x122\n" +
	"\x15effective_identity_id\x18\n" +
	" \x01(\tR\x13effectiveIdentityId\x12\x1c\n" +
	"\tauthority\x18\v \x01(\tR\tauthority\x12'\n" +
	"\x0fdecision_source\x18\f \x01(\tR\x0edecisionSource\x12\x1f\n" +
	"\vdecision_id\x18\r \x01(\tR\n" +
	"decisionId\x12\x1a\n" +
	"\bconflict\x18\x0e \x01(\tR\bconflict\x12M\n" +
	"$last_independent_evidence_at_unix_ns\x18\x0f \x01(\x06R\x1flastIndependentEvidenceAtUnixNs\x12\x1f\n" +
	"\vconfig_hash\x18\x10 \x01(\tR\n" +
	"configHash\x12*\n" +
	"\x11model_set_version\x18\x11 \x01(\tR\x0fmodelSetVersionR\x0fglobal_track_id\"y\n" +
	"\x11IdentityCandidate\x12\x1f\n" +
	"\videntity_id\x18\x01 \x01(\tR\n" +
	"identityId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12 \n" +
	"\vprobability\x18\x03 \x01(\x02R\vprobability\"\xd8\x01\n" +
	"\rPresenceEvent\x12\x13\n" +
	"\x05ph_id\x18\x01 \x01(\tR\x04phId\x12\x1f\n" +
	"\videntity_id\x18\x02 \x01(\tR\n" +
	"identityId\x12G\n" +
	"\n" +
	"event_type\x18\x03 \x01(\x0e2(.continuoustracking.v1.PresenceEventTypeR\teventType\x12\x1b\n" +
	"\troom_name\x18\x04 \x01(\tR\broomName\x12+\n" +
	"\x12event_time_unix_ns\x18\x05 \x01(\x06R\x0feventTimeUnixNs\"\xf1\x01\n" +
	"\n" +
	"DwellEvent\x12\x13\n" +
	"\x05ph_id\x18\x01 \x01(\tR\x04phId\x12\x1f\n" +
	"\videntity_id\x18\x02 \x01(\tR\n" +
	"identityId\x12D\n" +
	"\n" +
	"event_type\x18\x03 \x01(\x0e2%.continuoustracking.v1.DwellEventTypeR\teventType\x12\x1b\n" +
	"\troom_name\x18\x04 \x01(\tR\broomName\x12+\n" +
	"\x12event_time_unix_ns\x18\x05 \x01(\x06R\x0feventTimeUnixNs\x12\x1d\n" +
	"\n" +
	"duration_s\x18\x06 \x01(\x05R\tdurationS\"\xd2\x03\n" +
	"\x13CCIdentityAssertion\x12\x1b\n" +
	"\tperson_id\x18\x01 \x01(\tR\bpersonId\x12\x1b\n" +
	"\tcamera_id\x18\x02 \x01(\tR\bcameraId\x12-\n" +
	"\x13captured_at_unix_ns\x18\x03 \x01(\x06R\x10capturedAtUnixNs\x12\x1a\n" +
	"\tfloor_x_m\x18\x04 \x01(\x02R\afloorXM\x12\x1a\n" +
	"\tfloor_y_m\x18\x05 \x01(\x02R\afloorYM\x12%\n" +
	"\x0eraw_similarity\x18\x06 \x01(\x02R\rrawSimilarity\x128\n" +
	"\x15calibrated_confidence\x18\a \x01(\x02H\x00R\x14calibratedConfidence\x88\x01\x01\x12-\n" +
	"\x12calibration_status\x18\b \x01(\tR\x11calibrationStatus\x12\x16\n" +
	"\x06source\x18\t \x01(\tR\x06source\x12#\n" +
	"\rmodel_version\x18\n" +
	" \x01(\tR\fmodelVersion\x123\n" +
	"\x15preprocessing_version\x18\v \x01(\tR\x14preprocessingVersionB\x18\n" +
	"\x16_calibrated_confidence*\x7f\n" +
	"\x11PresenceEventType\x12#\n" +
	"\x1fPRESENCE_EVENT_TYPE_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cPRESENCE_EVENT_TYPE_APPEARED\x10\x01\x12#\n" +
	"\x1fPRESENCE_EVENT_TYPE_DISAPPEARED\x10\x02*l\n" +
	"\x0eDwellEventType\x12 \n" +
	"\x1cDWELL_EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18DWELL_EVENT_TYPE_STARTED\x10\x01\x12\x1a\n" +
	"\x16DWELL_EVENT_TYPE_ENDED\x10\x02*\xb8\x01\n" +
	"\x0fSceneSampleKind\x12!\n" +
	"\x1dSCENE_SAMPLE_KIND_UNSPECIFIED\x10\x00\x12%\n" +
	"!SCENE_SAMPLE_KIND_ISOLATED_PERSON\x10\x01\x12!\n" +
	"\x1dSCENE_SAMPLE_KIND_INTERACTION\x10\x02\x12\x1b\n" +
	"\x17SCENE_SAMPLE_KIND_CROWD\x10\x03\x12\x1b\n" +
	"\x17SCENE_SAMPLE_KIND_EMPTY\x10\x04BOZMgithub.com/SilverMind-Project/continuous-tracking/proto/continuoustracking/v1b\x06proto3"

var (
	file_continuoustracking_v1_tracking_proto_rawDescOnce sync.Once
	file_continuoustracking_v1_tracking_proto_rawDescData []byte
)

func file_continuoustracking_v1_tracking_proto_rawDescGZIP() []byte {
	file_continuoustracking_v1_tracking_proto_rawDescOnce.Do(func() {
		file_continuoustracking_v1_tracking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_continuoustracking_v1_tracking_proto_rawDesc), len(file_continuoustracking_v1_tracking_proto_rawDesc)))
	})
	return file_continuoustracking_v1_tracking_proto_rawDescData
}

var file_continuoustracking_v1_tracking_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_continuoustracking_v1_tracking_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_continuoustracking_v1_tracking_proto_goTypes = []any{
	(PresenceEventType)(0),      // 0: continuoustracking.v1.PresenceEventType
	(DwellEventType)(0),         // 1: continuoustracking.v1.DwellEventType
	(SceneSampleKind)(0),        // 2: continuoustracking.v1.SceneSampleKind
	(*TrackingEvent)(nil),       // 3: continuoustracking.v1.TrackingEvent
	(*FrameRef)(nil),            // 4: continuoustracking.v1.FrameRef
	(*Detection)(nil),           // 5: continuoustracking.v1.Detection
	(*PoseKeypoint)(nil),        // 6: continuoustracking.v1.PoseKeypoint
	(*TrailPoint)(nil),          // 7: continuoustracking.v1.TrailPoint
	(*PosteriorEvidence)(nil),   // 8: continuoustracking.v1.PosteriorEvidence
	(*BoundingBox)(nil),         // 9: continuoustracking.v1.BoundingBox
	(*FloorPoint)(nil),          // 10: continuoustracking.v1.FloorPoint
	(*IdentityRevision)(nil),    // 11: continuoustracking.v1.IdentityRevision
	(*IdentitySnapshot)(nil),    // 12: continuoustracking.v1.IdentitySnapshot
	(*IdentityCandidate)(nil),   // 13: continuoustracking.v1.IdentityCandidate
	(*PresenceEvent)(nil),       // 14: continuoustracking.v1.PresenceEvent
	(*DwellEvent)(nil),          // 15: continuoustracking.v1.DwellEvent
	(*CCIdentityAssertion)(nil), // 16: continuoustracking.v1.CCIdentityAssertion
}
var file_continuoustracking_v1_tracking_proto_depIdxs = []int32{
	4,  // 0: continuoustracking.v1.TrackingEvent.frame_ref:type_name -> continuoustracking.v1.FrameRef
	5,  // 1: continuoustracking.v1.TrackingEvent.detections:type_name -> continuoustracking.v1.Detection
	11, // 2: continuoustracking.v1.TrackingEvent.identity_revisions:type_name -> continuoustracking.v1.IdentityRevision
	12, // 3: continuoustracking.v1.TrackingEvent.identity_snapshots:type_name -> continuoustracking.v1.IdentitySnapshot
	9,  // 4: continuoustracking.v1.Detection.bbox:type_name -> continuoustracking.v1.BoundingBox
	10, // 5: continuoustracking.v1.Detection.floor_point:type_name -> continuoustracking.v1.FloorPoint
	6,  // 6: continuoustracking.v1.Detection.pose_keypoints:type_name -> continuoustracking.v1.PoseKeypoint
	7,  // 7: continuoustracking.v1.Detection.trail:type_name -> continuoustracking.v1.TrailPoint
	8,  // 8: continuoustracking.v1.Detection.evidence:type_name -> continuoustracking.v1.PosteriorEvidence
	13, // 9: continuoustracking.v1.IdentityRevision.candidates:type_name -> continuoustracking.v1.IdentityCandidate
	0,  // 10: continuoustracking.v1.PresenceEvent.event_type:type_name -> continuoustracking.v1.PresenceEventType
	1,  // 11: continuoustracking.v1.DwellEvent.event_type:type_name -> continuoustracking.v1.DwellEventType
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_continuoustracking_v1_tracking_proto_init() }
func file_continuoustracking_v1_tracking_proto_init() {
	if File_continuoustracking_v1_tracking_proto != nil {
		return
	}
	file_continuoustracking_v1_tracking_proto_msgTypes[13].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_continuoustracking_v1_tracking_proto_rawDesc), len(file_continuoustracking_v1_tracking_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_continuoustracking_v1_tracking_proto_goTypes,
		DependencyIndexes: file_continuoustracking_v1_tracking_proto_depIdxs,
		EnumInfos:         file_continuoustracking_v1_tracking_proto_enumTypes,
		MessageInfos:      file_continuoustracking_v1_tracking_proto_msgTypes,
	}.Build()
	File_continuoustracking_v1_tracking_proto = out.File
	file_continuoustracking_v1_tracking_proto_goTypes = nil
	file_continuoustracking_v1_tracking_proto_depIdxs = nil
}
