# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: continuoustracking/v1/signals.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'continuoustracking/v1/signals.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#continuoustracking/v1/signals.proto\x12\x15\x63ontinuoustracking.v1\"\xe3\x03\n\x0e\x44\x65mentiaSignal\x12\x11\n\tsignal_id\x18\x01 \x01(\t\x12\x13\n\x0bidentity_id\x18\x02 \x01(\t\x12\x37\n\x04kind\x18\x03 \x01(\x0e\x32).continuoustracking.v1.DementiaSignalKind\x12?\n\x08severity\x18\x04 \x01(\x0e\x32-.continuoustracking.v1.DementiaSignalSeverity\x12\r\n\x05value\x18\x05 \x01(\x02\x12\x14\n\x0chas_baseline\x18\x06 \x01(\x08\x12\x10\n\x08\x62\x61seline\x18\x07 \x01(\x02\x12\x13\n\x0bhas_z_score\x18\x08 \x01(\x08\x12\x0f\n\x07z_score\x18\t \x01(\x02\x12\x1c\n\x14window_start_unix_ns\x18\n \x01(\x06\x12\x1a\n\x12window_end_unix_ns\x18\x0b \x01(\x06\x12\x1a\n\x12\x65mitted_at_unix_ns\x18\x0c \x01(\x06\x12\x14\n\x0c\x63ontext_json\x18\r \x01(\t\x12\x19\n\x11\x61lgorithm_version\x18\x0e \x01(\x05\x12\x16\n\x0e\x61lgorithm_name\x18\x0f \x01(\t\x12\x16\n\x0e\x65vidence_grade\x18\x10 \x01(\t\x12\x1b\n\x13\x61lgorithm_spec_json\x18\x11 \x01(\t*\xac\x03\n\x12\x44\x65mentiaSignalKind\x12$\n DEMENTIA_SIGNAL_KIND_UNSPECIFIED\x10\x00\x12\x1f\n\x1b\x44\x45MENTIA_SIGNAL_KIND_PACING\x10\x01\x12)\n%DEMENTIA_SIGNAL_KIND_SUNDOWNING_INDEX\x10\x02\x12/\n+DEMENTIA_SIGNAL_KIND_BATHROOM_DWELL_ANOMALY\x10\x03\x12+\n\'DEMENTIA_SIGNAL_KIND_NIGHTTIME_MOVEMENT\x10\x04\x12*\n&DEMENTIA_SIGNAL_KIND_STILLNESS_ANOMALY\x10\x05\x12 \n\x1c\x44\x45MENTIA_SIGNAL_KIND_ABSENCE\x10\x06\x12\'\n#DEMENTIA_SIGNAL_KIND_FALL_SUSPECTED\x10\x07\x12%\n!DEMENTIA_SIGNAL_KIND_GAIT_SLOWING\x10\x08\x12(\n$DEMENTIA_SIGNAL_KIND_AGITATION_INDEX\x10\t*\xb3\x01\n\x16\x44\x65mentiaSignalSeverity\x12(\n$DEMENTIA_SIGNAL_SEVERITY_UNSPECIFIED\x10\x00\x12!\n\x1d\x44\x45MENTIA_SIGNAL_SEVERITY_INFO\x10\x01\x12$\n DEMENTIA_SIGNAL_SEVERITY_WARNING\x10\x02\x12&\n\"DEMENTIA_SIGNAL_SEVERITY_EMERGENCY\x10\x03\x42OZMgithub.com/SilverMind-Project/continuous-tracking/proto/continuoustracking/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'continuoustracking.v1.signals_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZMgithub.com/SilverMind-Project/continuous-tracking/proto/continuoustracking/v1'
  _globals['_DEMENTIASIGNALKIND']._serialized_start=549
  _globals['_DEMENTIASIGNALKIND']._serialized_end=977
  _globals['_DEMENTIASIGNALSEVERITY']._serialized_start=980
  _globals['_DEMENTIASIGNALSEVERITY']._serialized_end=1159
  _globals['_DEMENTIASIGNAL']._serialized_start=63
  _globals['_DEMENTIASIGNAL']._serialized_end=546
# @@protoc_insertion_point(module_scope)
